// vocab.js
// 2026 最新日K & 動漫J-POP高頻核心字庫 (精選1000組落地完整版)
const OFFLINE_VOCAB_DB = [
    // === 001 - 050: 命運、世界與希望篇 (動漫開場神曲高頻詞) ===
    { "kanji": "残酷", "kana": "ざんこく", "romaji": "zankoku", "meaning": "殘酷的 (殘酷天使的行動綱領)" },
    { "kanji": "天使", "kana": "てんし", "romaji": "tenshi", "meaning": "天使" },
    { "kanji": "神話", "kana": "しんわ", "romaji": "shinwa", "meaning": "神話" },
    { "kanji": "運命", "kana": "うんめい", "romaji": "unmei", "meaning": "命運" },
    { "kanji": "世界", "kana": "せかい", "romaji": "sekai", "meaning": "世界" },
    { "kanji": "秘密", "kana": "ひみつ", "romaji": "himitsu", "meaning": "秘密 (Idol 歌詞)" },
    { "kanji": "完璧", "kana": "かんぺき", "romaji": "kanpeki", "meaning": "完美的" },
    { "kanji": "未来", "kana": "みらい", "romaji": "mirai", "meaning": "未來" },
    { "kanji": "心", "kana": "こころ", "romaji": "kokoro", "meaning": "心、心靈" },
    { "kanji": "明日", "kana": "あした", "romaji": "ashita", "meaning": "明天" },
    { "kanji": "絆", "kana": "きずな", "romaji": "kizuna", "meaning": "羈絆" },
    { "kanji": "奇跡", "kana": "きせき", "romaji": "kiseki", "meaning": "奇蹟" },
    { "kanji": "情熱", "kana": "じょうねつ", "romaji": "jounetsu", "meaning": "熱情" },
    { "kanji": "孤独", "kana": "こどく", "romaji": "kodoku", "meaning": "孤獨" },
    { "kanji": "記憶", "kana": "きおく", "romaji": "kioku", "meaning": "記憶" },
    { "kanji": "真実", "kana": "しんじつ", "romaji": "shinjitsu", "meaning": "真實" },
    { "kanji": "永遠", "kana": "えいえん", "romaji": "eien", "meaning": "永遠" },
    { "kanji": "自由", "kana": "じゆう", "romaji": "jiyuu", "meaning": "自由 (進擊的巨人)" },
    { "kanji": "希望", "kana": "きぼう", "romaji": "kibou", "meaning": "希望" },
    { "kanji": "光", "kana": "ひかり", "romaji": "hikari", "meaning": "光芒" },
    { "kanji": "魂", "kana": "たましい", "romaji": "tamashii", "meaning": "靈魂" },
    { "kanji": "一歩", "kana": "いっぽ", "romaji": "ippo", "meaning": "一步" },
    { "kanji": "限界", "kana": "げんかい", "romaji": "genkai", "meaning": "極限" },
    { "kanji": "幻想", "kana": "げんそう", "romaji": "gensou", "meaning": "幻想" },
    { "kanji": "覚醒", "kana": "かくせい", "romaji": "kaksei", "meaning": "覺醒" },
    { "kanji": "扉", "kana": "とびら", "romaji": "tobira", "meaning": "門扉、序幕" },
    { "kanji": "神様", "kana": "かみさま", "romaji": "kamisama", "meaning": "神明" },
    { "kanji": "奇妙", "kana": "きみょう", "romaji": "kimyou", "meaning": "奇妙的 (JoJo)" },
    { "kanji": "冒険", "kana": "ぼうけん", "romaji": "bouken", "meaning": "冒險" },
    { "kanji": "血統", "kana": "けっとう", "romaji": "kettou", "meaning": "血統" },
    { "kanji": "標的", "kana": "ひょうてき", "romaji": "hyouteki", "meaning": "目標、靶子" },
    { "kanji": "伝説", "kana": "でんせつ", "romaji": "densetsu", "meaning": "傳說" },
    { "kanji": "風王", "kana": "ふうおう", "romaji": "fuuou", "meaning": "風王" },
    { "kanji": "聖杯", "kana": "せいはい", "romaji": "seihai", "meaning": "聖杯" },
    { "kanji": "契約", "kana": "けいやく", "romaji": "keiyaku", "meaning": "契約 (小圓/Fate)" },
    { "kanji": "魔法", "kana": "まほう", "romaji": "mahou", "meaning": "魔法" },
    { "kanji": "少女", "kana": "しょうじょ", "romaji": "shoujo", "meaning": "少女" },
    { "kanji": "奇蹟", "kana": "きせき", "romaji": "kiseki", "meaning": "奇蹟" },
    { "kanji": "等価交換", "kana": "とうかこうかん", "romaji": "toukakoukan", "meaning": "等價交換 (鋼鍊)" },
    { "kanji": "真理", "kana": "しんり", "romaji": "shinri", "meaning": "真理" },
    { "kanji": "錬金術", "kana": "れんきんじゅつ", "romaji": "renkinjutsu", "meaning": "鍊金術" },
    { "kanji": "旅立ち", "kana": "たびだち", "romaji": "tabidachi", "meaning": "啟程" },
    { "kanji": "新世界", "kana": "しんせかい", "romaji": "shinsekai", "meaning": "新世界" },
    { "kanji": "王座", "kana": "おうざ", "romaji": "ouza", "meaning": "王座" },
    { "kanji": "支配", "kana": "しはい", "romaji": "shihai", "meaning": "支配" },
    { "kanji": "終焉", "kana": "しゅうえん", "romaji": "shuuen", "meaning": "終焉" },
    { "kanji": "創世記", "kana": "そうせいき", "romaji": "souseiki", "meaning": "創世紀" },
    { "kanji": "神話", "kana": "しんわ", "romaji": "shinwa", "meaning": "神話" },
    { "kanji": "光輝", "kana": "こうき", "romaji": "kouki", "meaning": "光輝" },
    { "kanji": "漆黒", "kana": "しっこく", "romaji": "shikkoku", "meaning": "漆黑" },

    // === 051 - 100: 戰鬥、鮮血與熱血篇 (鬼滅、咒術、火影系列) ===
    { "kanji": "紅蓮", "kana": "ぐれん", "romaji": "guren", "meaning": "紅蓮 (紅蓮華)" },
    { "kanji": "運命", "kana": "さだめ", "romaji": "sadame", "meaning": "宿命 (常唱作さだめ)" },
    { "kanji": "泥", "kana": "どろ", "romaji": "doro", "meaning": "泥巴" },
    { "kanji": "刃", "kana": "やいば", "romaji": "yaiba", "meaning": "刀刃" },
    { "kanji": "強さ", "kana": "つよさ", "romaji": "tsuyosa", "meaning": "堅強、力量" },
    { "kanji": "呪い", "kana": "のろい", "romaji": "noroi", "meaning": "詛咒" },
    { "kanji": "廻廻", "kana": "かいかい", "romaji": "kaikai", "meaning": "迴迴" },
    { "kanji": "青空", "kana": "あおぞら", "romaji": "aozora", "meaning": "藍天" },
    { "kanji": "蒼い", "kana": "あおい", "romaji": "aoi", "meaning": "藍色的 (青鳥)" },
    { "kanji": "悲しみ", "kana": "かなしみ", "romaji": "kanashimi", "meaning": "悲傷" },
    { "kanji": "羽ばたく", "kana": "はばたく", "romaji": "habataku", "meaning": "展翅高飛" },
    { "kanji": "鼓動", "kana": "こどう", "romaji": "kodou", "meaning": "心跳、鼓動" },
    { "kanji": "宿命", "kana": "しゅくめい", "romaji": "shukumei", "meaning": "宿命" },
    { "kanji": "衝動", "kana": "しょうどう", "romaji": "shoudou", "meaning": "衝動" },
    { "kanji": "正義", "kana": "せいぎ", "romaji": "seigi", "meaning": "正義" },
    { "kanji": "覚悟", "kana": "かくご", "romaji": "kakugo", "meaning": "覺悟" },
    { "kanji": "絶望", "kana": "ぜつぼう", "romaji": "zetsubou", "meaning": "絕望" },
    { "kanji": "勝利", "kana": "しょうり", "romaji": "shouri", "meaning": "勝利" },
    { "kanji": "敗北", "kana": "はいぼく", "romaji": "haiboku", "meaning": "敗北" },
    { "kanji": "暗闇", "kana": "くらやみ", "romaji": "kurayami", "meaning": "黑暗" },
    { "kanji": "稲妻", "kana": "いなずま", "romaji": "inazuma", "meaning": "閃電" },
    { "kanji": "烈火", "kana": "れっか", "romaji": "rekka", "meaning": "烈火" },
    { "kanji": "闘志", "kana": "とうし", "romaji": "toushi", "meaning": "鬥志" },
    { "kanji": "修羅", "kana": "しゅら", "romaji": "shura", "meaning": "修羅" },
    { "kanji": "戦場", "kana": "せんじょう", "romaji": "senjou", "meaning": "戰場" },
    { "kanji": "烽火", "kana": "ほうか", "romaji": "houka", "meaning": "烽火" },
    { "kanji": "斬擊", "kana": "ざんげき", "romaji": "zangeki", "meaning": "斬擊" },
    { "kanji": "特級", "kana": "とっきゅう", "romaji": "tokkyuu", "meaning": "特級" },
    { "kanji": "領域展開", "kana": "りょういきてんかい", "romaji": "ryouikitenkai", "meaning": "領域展開 (咒術迴戰)" },
    { "kanji": "黒閃", "kana": "こくせん", "romaji": "koksen", "meaning": "黑閃" },
    { "kanji": "全集中", "kana": "ぜんしゅうちゅう", "romaji": "zenshuuchuu", "meaning": "全集中" },
    { "kanji": "呼吸", "kana": "こきゅう", "romaji": "kokyuu", "meaning": "呼吸" },
    { "kanji": "赫", "kana": "あか", "romaji": "aka", "meaning": "赫/紅" },
    { "kanji": "一撃", "kana": "いちげき", "romaji": "ichigeki", "meaning": "一擊" },
    { "kanji": "宿敵", "kana": "しゅくてき", "romaji": "shukuteki", "meaning": "宿敵" },
    { "kanji": "血潮", "kana": "ちしお", "romaji": "chishio", "meaning": "熱血、血潮" },
    { "kanji": "死線", "kana": "しせん", "romaji": "shisen", "meaning": "死線" },
    { "kanji": "反撃", "kana": "はんげき", "romaji": "hangeki", "meaning": "反擊" },
    { "kanji": "咆哮", "kana": "ほうこう", "romaji": "houkou", "meaning": "咆哮" },
    { "kanji": "激闘", "kana": "げきとう", "romaji": "gekitou", "meaning": "激鬥" },
    { "kanji": "不死身", "kana": "ふじみ", "romaji": "fujimi", "meaning": "不死之身" },
    { "kanji": "奥義", "kana": "おうぎ", "romaji": "ougi", "meaning": "奧義" },
    { "kanji": "覇気", "kana": "はき", "romaji": "haki", "meaning": "霸氣" },
    { "kanji": "誇り", "kana": "ほこり", "romaji": "hokori", "meaning": "驕傲、自豪" },
    { "kanji": "屈辱", "kana": "くつじょく", "romaji": "kutsujoku", "meaning": "屈辱" },
    { "kanji": "復讐", "kana": "ふくしゅう", "romaji": "fukushuu", "meaning": "復仇" },
    { "kanji": "牙", "kana": "きば", "romaji": "kiba", "meaning": "獠牙" },
    { "kanji": "爪", "kana": "つめ", "romaji": "tsume", "meaning": "利爪" },
    { "kanji": "肉体", "kana": "にくたい", "romaji": "nikutai", "meaning": "肉體" },
    { "kanji": "限界突破", "kana": "げんかいとっぱ", "romaji": "genkaitoppa", "meaning": "突破極限" },

    // === 101 - 150: 星空、夜晚與都市感篇 (YOASOBI、Vaundy、美音) ===
    { "kanji": "夜", "kana": "よる", "romaji": "yoru", "meaning": "夜晚 (向夜晚奔去)" },
    { "kanji": "駆ける", "kana": "かける", "romaji": "kakeru", "meaning": "奔跑" },
    { "kanji": "沈む", "kana": "しずむ", "romaji": "shizumu", "meaning": "下沉" },
    { "kanji": "怪獣", "kana": "かいじゅう", "romaji": "kaijuu", "meaning": "怪獸 (怪獸的花歌)" },
    { "kanji": "花唄", "kana": "はなうた", "romaji": "hanauta", "meaning": "哼歌、花歌" },
    { "kanji": "踊り", "kana": "おどり", "romaji": "odori", "meaning": "舞蹈 (Ado - 踊)" },
    { "kanji": "新時代", "kana": "しんじだい", "romaji": "shinjidai", "meaning": "新時代 (ONE PIECE FILM RED)" },
    { "kanji": "東京", "kana": "とうきょう", "romaji": "toukyou", "meaning": "東京" },
    { "kanji": "逆光", "kana": "ぎゃっこう", "romaji": "gyakkou", "meaning": "逆光" },
    { "kanji": "残響", "kana": "ざんきょう", "romaji": "zankyou", "meaning": "殘響 (殘響散歌)" },
    { "kanji": "散歌", "kana": "さんか", "romaji": "sanka", "meaning": "散歌" },
    { "kanji": "朝霧", "kana": "あさぎり", "romaji": "asagiri", "meaning": "晨霧" },
    { "kanji": "真夜中", "kana": "まよなか", "romaji": "mayonaka", "meaning": "午夜、連夜" },
    { "kanji": "星座", "kana": "せいざ", "romaji": "seiza", "meaning": "星座" },
    { "kanji": "流星", "kana": "りゅうせい", "romaji": "ryuusei", "meaning": "流星" },
    { "kanji": "銀河", "kana": "ぎんが", "romaji": "ginga", "meaning": "銀河" },
    { "kanji": "彗星", "kana": "すいせい", "romaji": "suisei", "meaning": "彗星" },
    { "kanji": "月光", "kana": "げっこう", "romaji": "gekkou", "meaning": "月光" },
    { "kanji": "夜明け", "kana": "よあけ", "romaji": "yoake", "meaning": "黎明、拂曉" },
    { "kanji": "都会", "kana": "とかい", "romaji": "tokai", "meaning": "都市" },
    { "kanji": "喧騒", "kana": "けんそう", "romaji": "kensou", "meaning": "喧囂" },
    { "kanji": "静寂", "kana": "せいじゃく", "romaji": "seijaku", "meaning": "寂靜" },
    { "kanji": "ネオン", "kana": "ねおん", "romaji": "neon", "meaning": "霓虹燈" },
    { "kanji": "ステップ", "kana": "すてっぷ", "romaji": "suteppu", "meaning": "舞步 (Step)" },
    { "kanji": "メロディ", "kana": "めろでぃ", "romaji": "merodi", "meaning": "旋律" },
    { "kanji": "群青", "kana": "ぐんじょう", "romaji": "gunjou", "meaning": "群青 (YOASOBI)" },
    { "kanji": "夜空", "kana": "よぞら", "romaji": "yozora", "meaning": "夜空" },
    { "kanji": "星屑", "kana": "ほしくず", "romaji": "hoshikuzu", "meaning": "星屑、星塵" },
    { "kanji": "瞬き", "kana": "まばたき", "romaji": "mabataki", "meaning": "眨眼、閃爍" },
    { "kanji": "摩天楼", "kana": "まてんろう", "romaji": "matenrou", "meaning": "摩天大樓" },
    { "kanji": "交差点", "kana": "こうさてん", "romaji": "kousaten", "meaning": "十字路口" },
    { "kanji": "信号", "kana": "しんごう", "romaji": "shingou", "meaning": "紅綠燈" },
    { "kanji": "影法師", "kana": "かげぼうし", "romaji": "kageboushi", "meaning": "影子" },
    { "kanji": "残像", "kana": "ざんぞう", "romaji": "zanzou", "meaning": "殘像" },
    { "kanji": "幻影", "kana": "げんえい", "romaji": "genei", "meaning": "幻影" },
    { "kanji": "薄明かり", "kana": "うすあかり", "romaji": "usuakari", "meaning": "微光" },
    { "kanji": "終電", "kana": "しゅうでん", "romaji": "shuuden", "meaning": "末班車" },
    { "kanji": "線路", "kana": "せんろ", "romaji": "senro", "meaning": "鐵軌" },
    { "kanji": "車窗", "kana": "しゃそう", "romaji": "shasou", "meaning": "車窗" },
    { "kanji": "ヘッドホン", "kana": "へっどほん", "romaji": "heddohon", "meaning": "耳機" },
    { "kanji": "雑音", "kana": "ざつおん", "romaji": "zatsuon", "meaning": "噪音" },
    { "kanji": "深夜", "kana": "しんや", "romaji": "shinya", "meaning": "深夜" },
    { "kanji": "黎明", "kana": "れいめい", "romaji": "reimei", "meaning": "黎明" },
    { "kanji": "トワイライト", "kana": "とわいらいと", "romaji": "towairaito", "meaning": "暮光、黃昏" },
    { "kanji": "シティポップ", "kana": "していぽっぷ", "romaji": "shitipoppu", "meaning": "城市流行 (City Pop)" },
    { "kanji": "夜風", "kana": "よかぜ", "romaji": "yokaze", "meaning": "夜風" },
    { "kanji": "ダンスナンバー", "kana": "だんすなんばー", "romaji": "dansunanbaー", "meaning": "舞曲" },
    { "kanji": "リズムボックス", "kana": "りずむぼっくす", "romaji": "rizumubokksu", "meaning": "節奏機" },
    { "kanji": "ミラーボール", "kana": "みらーぼーる", "romaji": "miraーboーru", "meaning": "鏡球" },
    { "kanji": "カクテル", "kana": "かくてる", "romaji": "kakuteru", "meaning": "雞尾酒" },

    // === 151 - 200: 情感、淚水與思念篇 (青春、抒情歌、日K必點) ===
    { "kanji": "愛", "kana": "あい", "romaji": "ai", "meaning": "愛" },
    { "kanji": "恋", "kana": "こい", "romaji": "koi", "meaning": "戀愛 (星野源 - 戀)" },
    { "kanji": "涙", "kana": "なみだ", "romaji": "namida", "meaning": "淚水" },
    { "kanji": "笑顔", "kana": "えがお", "romaji": "egao", "meaning": "笑容" },
    { "kanji": "瞳", "kana": "ひとみ", "romaji": "hitomi", "meaning": "眼睛、瞳孔" },
    { "kanji": "嘘", "kana": "うそ", "romaji": "uso", "meaning": "謊言" },
    { "kanji": "初恋", "kana": "はつこい", "romaji": "hatsukoi", "meaning": "初戀" },
    { "kanji": "言葉", "kana": "ことば", "romaji": "kotoba", "meaning": "言語、字句" },
    { "kanji": "約束", "kana": "やくそく", "romaji": "yaksoku", "meaning": "約定" },
    { "kanji": "さよなり", "kana": "さよなら", "romaji": "sayonara", "meaning": "再見" },
    { "kanji": "ありがとう", "kana": "ありがとう", "romaji": "arigatou", "meaning": "謝謝" },
    { "kanji": "切ない", "kana": "せつない", "romaji": "setsunai", "meaning": "難過的、苦悶的" },
    { "kanji": "愛しい", "kana": "いとしい", "romaji": "itoshii", "meaning": "心愛的" },
    { "kanji": "恋人", "kana": "こいびと", "romaji": "koibito", "meaning": "戀人" },
    { "kanji": "温もり", "kana": "ぬくもり", "romaji": "nukumori", "meaning": "溫度、溫暖" },
    { "kanji": "溜息", "kana": "ためいき", "romaji": "tameiki", "meaning": "嘆氣" },
    { "kanji": "出会い", "kana": "であい", "romaji": "deai", "meaning": "相遇" },
    { "kanji": "別れ", "kana": "わかれ", "romaji": "wakare", "meaning": "離別" },
    { "kanji": "面影", "kana": "おもかげ", "romaji": "omokage", "meaning": "容貌、身影" },
    { "kanji": "胸", "kana": "むね", "romaji": "mune", "meaning": "胸口、內心" },
    { "kanji": "優しさ", "kana": "やさしさ", "romaji": "yasashisa", "meaning": "溫柔" },
    { "kanji": "嫉妬", "kana": "しっと", "romaji": "shitto", "meaning": "嫉妒" },
    { "kanji": "恋慕", "kana": "れんぼ", "romaji": "renbo", "meaning": "戀慕" },
    { "kanji": "片思い", "kana": "かたおもい", "romaji": "kataomoi", "meaning": "單戀" },
    { "kanji": "両思い", "kana": "りょうおもい", "romaji": "ryouomoi", "meaning": "雙向奔赴、相戀" },
    { "kanji": "告白", "kana": "こくはく", "romaji": "kokuhaku", "meaning": "告白" },
    { "kanji": "未練", "kana": "みれん", "romaji": "miren", "meaning": "依戀、留戀" },
    { "kanji": "執着", "kana": "しゅうちゃく", "romaji": "shuuchaku", "meaning": "執著" },
    { "kanji": "嫉妬", "kana": "しっと", "romaji": "shitto", "meaning": "嫉妒" },
    { "kanji": "羨望", "kana": "せんぼう", "romaji": "senbou", "meaning": "羨慕" },
    { "kanji": "純情", "kana": "じゅんじょう", "romaji": "junjou", "meaning": "純情" },
    { "kanji": "情愛", "kana": "じょうあい", "romaji": "jouai", "meaning": "情愛" },
    { "kanji": "葛藤", "kana": "かっとう", "romaji": "kattou", "meaning": "糾結、葛藤" },
    { "kanji": "本心", "kana": "ほんしん", "romaji": "honshin", "meaning": "真心話" },
    { "kanji": "偽り", "kana": "いつわり", "romaji": "itsuwari", "meaning": "虛假、偽裝" },
    { "kanji": "強がり", "kana": "つよがり", "romaji": "tsuyogari", "meaning": "逞強" },
    { "kanji": "弱音", "kana": "よわね", "romaji": "yowane", "meaning": "洩氣話" },
    { "kanji": "涙腺", "kana": "るいせん", "romaji": "ruisen", "meaning": "淚腺" },
    { "kanji": "微笑み", "kana": "ほほえみ", "romaji": "hohoemi", "meaning": "微笑" },
    { "kanji": "歓喜", "kana": "かんき", "romaji": "kanki", "meaning": "歡喜" },
    { "kanji": "哀愁", "kana": "あいしゅう", "romaji": "aishuu", "meaning": "哀愁" },
    { "kanji": "郷愁", "kana": "きょうしゅう", "romaji": "kyoushuu", "meaning": "鄉愁" },
    { "kanji": "愛憎", "kana": "あいぞう", "romaji": "aizou", "meaning": "愛恨" },
    { "kanji": "感傷", "kana": "かんしょう", "romaji": "kanshou", "meaning": "感傷" },
    { "kanji": "切なさ", "kana": "せつなさ", "romaji": "setsunasa", "meaning": "苦悶感" },
    { "kanji": "愛おしい", "kana": "いとおしい", "romaji": "itooshii", "meaning": "可愛的、可憐的" },
    { "kanji": "初々しい", "kana": "ういういしい", "romaji": "uiuiishii", "meaning": "天真單純的" },
    { "kanji": "愛嬌", "kana": "あいきょう", "romaji": "aikyou", "meaning": "撒嬌、魅力的" },
    { "kanji": "純粋", "kana": "じゅんすい", "romaji": "junsui", "meaning": "純粹" },
    { "kanji": "本音", "kana": "ほんね", "romaji": "honne", "meaning": "真心話" },

    // === 201 - 250: 四季、大自然與景象篇 ===
    { "kanji": "桜", "kana": "さくら", "romaji": "sakura", "meaning": "櫻花" },
    { "kanji": "花火", "kana": "はなび", "romaji": "hanabi", "meaning": "煙火 (米津玄師 - 打上花火)" },
    { "kanji": "向日葵", "kana": "ひまわり", "romaji": "himawari", "meaning": "向日葵" },
    { "kanji": "紅葉", "kana": "もみじ", "romaji": "momiji", "meaning": "楓葉" },
    { "kanji": "雪", "kana": "ゆき", "romaji": "yuki", "meaning": "雪" },
    { "kanji": "吹雪", "kana": "ふぶき", "romaji": "fubuki", "meaning": "暴風雪" },
    { "kanji": "海", "kana": "うみ", "romaji": "umi", "meaning": "海洋" },
    { "kanji": "海岸", "kana": "かいがん", "romaji": "kaigan", "meaning": "海岸" },
    { "kanji": "風", "kana": "かぜ", "romaji": "kaze", "meaning": "微風" },
    { "kanji": "嵐", "kana": "あらし", "romaji": "arashi", "meaning": "暴風雨" },
    { "kanji": "太陽", "kana": "たいよう", "romaji": "taiyou", "meaning": "太陽" },
    { "kanji": "夕日", "kana": "ゆうひ", "romaji": "yuuhi", "meaning": "夕陽" },
    { "kanji": "茜色", "kana": "あかねいろ", "romaji": "akaneiro", "meaning": "暗紅色、茜草色" },
    { "kanji": "四季", "kana": "しき", "romaji": "shiki", "meaning": "四季" },
    { "kanji": "季節", "kana": "きせつ", "romaji": "kisetsu", "meaning": "季節" },
    { "kanji": "春", "kana": "はる", "romaji": "haru", "meaning": "春天" },
    { "kanji": "夏", "kana": "なつ", "romaji": "natsu", "meaning": "夏天" },
    { "kanji": "秋", "kana": "あき", "romaji": "aki", "meaning": "秋天" },
    { "kanji": "冬", "kana": "ふゆ", "romaji": "fuyu", "meaning": "冬天" },
    { "kanji": "大自然", "kana": "だいしぜん", "romaji": "daishizen", "meaning": "大自然" },
    { "kanji": "雲", "kana": "くも", "romaji": "kumo", "meaning": "雲朵" },
    { "kanji": "雨", "kana": "あめ", "romaji": "ame", "meaning": "下雨" },
    { "kanji": "虹", "kana": "にじ", "romaji": "niji", "meaning": "彩虹" },
    { "kanji": "大地", "kana": "だいち", "romaji": "daichi", "meaning": "大地" },
    { "kanji": "地平線", "kana": "ちへいせん", "romaji": "chiheisen", "meaning": "地平線" },
    { "kanji": "新緑", "kana": "しんりょく", "romaji": "shinryoku", "meaning": "新綠" },
    { "kanji": "木漏れ日", "kana": "こもれび", "romaji": "komorebi", "meaning": "樹蔭下漏出來的光" },
    { "kanji": "五月雨", "kana": "さみだれ", "romaji": "samidare", "meaning": "梅雨、五月雨" },
    { "kanji": "夕立", "kana": "ゆうだち", "romaji": "yuudachi", "meaning": "雷陣雨、午後陣雨" },
    { "kanji": "稲穂", "kana": "いなほ", "romaji": "inaho", "meaning": "稻穗" },
    { "kanji": "落葉", "kana": "らくよう", "romaji": "rakuyou", "meaning": "落葉" },
    { "kanji": "初雪", "kana": "はつゆき", "romaji": "hatsuyuki", "meaning": "初雪" },
    { "kanji": "氷河", "kana": "ひょうが", "romaji": "hyouga", "meaning": "冰河" },
    { "kanji": "猛暑", "kana": "もうしょ", "romaji": "mousho", "meaning": "酷暑" },
    { "kanji": "極寒", "kana": "ごっかん", "romaji": "gokkan", "meaning": "極寒" },
    { "kanji": "波浪", "kana": "はろう", "romaji": "harou", "meaning": "波浪" },
    { "kanji": "潮風", "kana": "しおかぜ", "romaji": "shiokaze", "meaning": "海風" },
    { "kanji": "砂浜", "kana": "すなはま", "romaji": "sunahama", "meaning": "沙灘" },
    { "kanji": "満月", "kana": "まんげつ", "romaji": "mangetsu", "meaning": "滿月" },
    { "kanji": "三日月", "kana": "みかづき", "romaji": "mikadzuki", "meaning": "新月、弦月" },
    { "kanji": "新月", "kana": "しんげつ", "romaji": "shingetsu", "meaning": "新月" },
    { "kanji": "群星", "kana": "ぐんせい", "romaji": "gunsei", "meaning": "群星" },
    { "kanji": "曙", "kana": "あけぼの", "romaji": "akebono", "meaning": "拂曉" },
    { "kanji": "黃昏", "kana": "たそがれ", "romaji": "tasogare", "meaning": "黃昏" },
    { "kanji": "宵闇", "kana": "よいやみ", "romaji": "yoiyami", "meaning": "暮色、初夜的黑暗" },
    { "kanji": "常夏", "kana": "とこなつ", "romaji": "tokonatsu", "meaning": "常夏" },
    { "kanji": "陽炎", "kana": "かげろう", "romaji": "kagerou", "meaning": "海市蜃樓、熱氣" },
    { "kanji": "蜃気楼", "kana": "しんきろう", "romaji": "shinkirou", "meaning": "海市蜃樓" },
    { "kanji": "地響き", "kana": "じひびき", "romaji": "jihibiki", "meaning": "大地轟鳴" },
    { "kanji": "落雷", "kana": "らくらい", "romaji": "rakurai", "meaning": "落雷" },

    // === 251 - 300: 樂器、音響與舞台演唱篇 (MyGO!!!!!、樂團感) ===
    { "kanji": "歌", "kana": "うた", "romaji": "uta", "meaning": "歌曲" },
    { "kanji": "唄", "kana": "うた", "romaji": "uta", "meaning": "古風/傳統歌謠" },
    { "kanji": "歌手", "kana": "かしゅ", "romaji": "kashu", "meaning": "歌手" },
    { "kanji": "歌詞", "kana": "かし", "romaji": "kashi", "meaning": "歌詞" },
    { "kanji": "音", "kana": "おと", "romaji": "oto", "meaning": "聲音" },
    { "kanji": "響き", "kana": "ひびき", "romaji": "hibiki", "meaning": "迴響、共鳴" },
    { "kanji": "楽器", "kana": "がっき", "romaji": "gakki", "meaning": "樂器" },
    { "kanji": "音響", "kana": "おんきょう", "romaji": "onkyou", "meaning": "音響" },
    { "kanji": "声", "kana": "こえ", "romaji": "koe", "meaning": "歌聲、人聲" },
    { "kanji": "叫び", "kana": "さけび", "romaji": "sakebi", "meaning": "吶喊" },
    { "kanji": "拍手", "kana": "はくしゅ", "romaji": "hakshu", "meaning": "鼓掌" },
    { "kanji": "舞台", "kana": "ぶたい", "romaji": "butai", "meaning": "舞台" },
    { "kanji": "奏でる", "kana": "かなでる", "romaji": "kanaderu", "meaning": "演奏" },
    { "kanji": "ピアノ", "kana": "ぴあの", "romaji": "piano", "meaning": "鋼琴" },
    { "kanji": "ギター", "kana": "ぎたー", "romaji": "gitaー", "meaning": "吉他" },
    { "kanji": "ドラム", "kana": "どらむ", "romaji": "doramu", "meaning": "爵士鼓" },
    { "kanji": "ベース", "kana": "べーす", "romaji": "beーsu", "meaning": "貝斯" },
    { "kanji": "リズム", "kana": "りずむ", "romaji": "rizumu", "meaning": "節奏" },
    { "kanji": "ライブ", "kana": "らいぶ", "romaji": "raibu", "meaning": "現場演唱會" },
    { "kanji": "バンド", "kana": "ばんど", "romaji": "bando", "meaning": "樂團" },
    { "kanji": "音符", "kana": "おんぷ", "romaji": "onpu", "meaning": "音符" },
    { "kanji": "和音", "kana": "わおん", "romaji": "waon", "meaning": "和弦" },
    { "kanji": "大歓声", "kana": "だいかんせい", "romaji": "daikansei", "meaning": "全場歡呼聲" },
    { "kanji": "調律", "kana": "ちょうりつ", "romaji": "chouritsu", "meaning": "調音、調律" },
    { "kanji": "旋律", "kana": "せんりつ", "romaji": "senritsu", "meaning": "旋律" },
    { "kanji": "和声", "kana": "わせい", "romaji": "wasei", "meaning": "和聲" },
    { "kanji": "協奏曲", "kana": "きょうそうきょく", "romaji": "kyousoukyoku", "meaning": "協奏曲" },
    { "kanji": "交響曲", "kana": "こうきょうきょく", "romaji": "koukyoukyoku", "meaning": "交響曲" },
    { "kanji": "独奏", "kana": "どくそう", "romaji": "dokusou", "meaning": "獨奏" },
    { "kanji": "伴奏", "kana": "ばんそう", "romaji": "bansou", "meaning": "伴奏" },
    { "kanji": "鍵盤", "kana": "けんばん", "romaji": "kenban", "meaning": "鍵盤" },
    { "kanji": "弦", "kana": "げん", "romaji": "gen", "meaning": "琴弦" },
    { "kanji": "楽譜", "kana": "がくふ", "romaji": "gakfu", "meaning": "樂譜" },
    { "kanji": "譜面", "kana": "ふめん", "romaji": "fumen", "meaning": "譜面" },
    { "kanji": "音階", "kana": "おんかい", "romaji": "onkai", "meaning": "音階" },
    { "kanji": "音量", "kana": "おんりょう", "romaji": "onryou", "meaning": "音量" },
    { "kanji": "爆音", "kana": "ばくおん", "romaji": "bakuon", "meaning": "爆音" },
    { "kanji": "轟音", "kana": "ごうおん", "romaji": "gouon", "meaning": "轟鳴聲" },
    { "kanji": "前奏", "kana": "ぜんそう", "romaji": "zensou", "meaning": "前奏" },
    { "kanji": "間奏", "kana": "かんそう", "romaji": "kansou", "meaning": "間奏" },
    { "kanji": "後奏", "kana": "こうそう", "romaji": "kousou", "meaning": "尾奏" },
    { "kanji": "主題歌", "kana": "しゅだいか", "romaji": "shudaika", "meaning": "主題曲" },
    { "kanji": "挿入歌", "kana": "そうにゅうか", "romaji": "sounyuuka", "meaning": "插曲" },
    { "kanji": "名曲", "kana": "めいきょく", "romaji": "meikyoku", "meaning": "名曲" },
    { "kanji": "神曲", "kana": "かみきょく", "romaji": "kamikyoku", "meaning": "神曲" },
    { "kanji": "即興", "kana": "そっきょう", "romaji": "sokkyou", "meaning": "即興" },
    { "kanji": "合唱", "kana": "がっしょう", "romaji": "gasshou", "meaning": "合唱" },
    { "kanji": "熱唱", "kana": "ねっしょう", "romaji": "nesshou", "meaning": "熱唱" },
    { "kanji": "裏声", "kana": "うらごえ", "romaji": "uragoe", "meaning": "假音" },
    { "kanji": "美声", "kana": "びせい", "romaji": "bisei", "meaning": "美聲" },

    // === 301 - 350: 動作、速度與時間流逝篇 ===
    { "kanji": "走る", "kana": "はしる", "romaji": "hashiru", "meaning": "奔跑" },
    { "kanji": "跳ぶ", "kana": "とぶ", "romaji": "tobu", "meaning": "跳躍" },
    { "kanji": "叫ぶ", "kana": "さけぶ", "romaji": "sakebu", "meaning": "高喊" },
    { "kanji": "祈る", "kana": "いのる", "romaji": "inoru", "meaning": "祈禱" },
    { "kanji": "願う", "kana": "ねがう", "romaji": "negau", "meaning": "願望、期盼" },
    { "kanji": "忘れる", "kana": "わすれる", "romaji": "wasureru", "meaning": "忘記" },
    { "kanji": "覚える", "kana": "おぼえる", "romaji": "oboeru", "meaning": "記住" },
    { "kanji": "探す", "kana": "さがす", "romaji": "sagasu", "meaning": "尋找" },
    { "kanji": "見つける", "kana": "みつける", "romaji": "mitsukeru", "meaning": "找到" },
    { "kanji": "信じる", "kana": "しんじる", "romaji": "shinjiru", "meaning": "相信" },
    { "kanji": "迷う", "kana": "まよう", "romaji": "mayou", "meaning": "迷茫、迷路" },
    { "kanji": "始まる", "kana": "はじまる", "romaji": "hajimaru", "meaning": "開始" },
    { "kanji": "終わる", "kana": "おわる", "romaji": "owaru", "meaning": "結束" },
    { "kanji": "進む", "kana": "すすむ", "romaji": "susumu", "meaning": "前進" },
    { "kanji": "戻る", "kana": "もどる", "romaji": "modoru", "meaning": "返回" },
    { "kanji": "加速", "kana": "かそく", "romaji": "kasoku", "meaning": "加速" },
    { "kanji": "瞬間", "kana": "しゅんかん", "romaji": "shunkan", "meaning": "瞬間" },
    { "kanji": "時間", "kana": "じかん", "romaji": "jikan", "meaning": "時間" },
    { "kanji": "時代", "kana": "じだい", "romaji": "jidai", "meaning": "時代" },
    { "kanji": "歴史", "kana": "れきし", "romaji": "rekishi", "meaning": "歷史" },
    { "kanji": "過去", "kana": "かこ", "romaji": "kako", "meaning": "過去" },
    { "kanji": "現在", "kana": "げんざい", "romaji": "genzai", "meaning": "現在" },
    { "kanji": "刹那", "kana": "せつな", "romaji": "setsuna", "meaning": "剎那" },
    { "kanji": "時計", "kana": "とけい", "romaji": "tokei", "meaning": "時鐘" },
    { "kanji": "疾走", "kana": "しっそう", "romaji": "shissou", "meaning": "疾馳、奔跑" },
    { "kanji": "飛翔", "kana": "ひしょう", "romaji": "hishou", "meaning": "飛翔" },
    { "kanji": "跳躍", "kana": "ちょうやく", "romaji": "chouyaku", "meaning": "跳躍" },
    { "kanji": "急行", "kana": "きゅうこう", "romaji": "kyuukou", "meaning": "急行、特快" },
    { "kanji": "遅延", "kana": "ちえん", "romaji": "chien", "meaning": "延遲" },
    { "kanji": "停止", "kana": "ていし", "romaji": "teishi", "meaning": "停止" },
    { "kanji": "永劫", "kana": "えいごう", "romaji": "eigou", "meaning": "永劫、萬世" },
    { "kanji": "一瞬", "kana": "いっしゅん", "romaji": "isshun", "meaning": "一瞬" },
    { "kanji": "秒針", "kana": "びょうしん", "romaji": "byoushin", "meaning": "秒針" },
    { "kanji": "長針", "kana": "ちょうしん", "romaji": "choushin", "meaning": "分針" },
    { "kanji": "短針", "kana": "たんしん", "romaji": "tanshin", "meaning": "時針" },
    { "kanji": "逆流", "kana": "ぎゃくりゅう", "romaji": "gyakuryuu", "meaning": "逆流" },
    { "kanji": "回帰", "kana": "かいき", "romaji": "kaiki", "meaning": "回歸" },
    { "kanji": "往復", "kana": "おうふく", "romaji": "oufuku", "meaning": "往返" },
    { "kanji": "永遠", "kana": "えいえん", "romaji": "eien", "meaning": "永遠" },
    { "kanji": "無限", "kana": "むげん", "romaji": "mugen", "meaning": "無限" },
    { "kanji": "有限", "kana": "ゆうげん", "romaji": "yuugen", "meaning": "有限" },
    { "kanji": "開宴", "kana": "かいえん", "romaji": "kaien", "meaning": "開宴" },
    { "kanji": "終宴", "kana": "しゅうえん", "romaji": "shuuen", "meaning": "散席、終宴" },
    { "kanji": "継続", "kana": "けいぞく", "romaji": "keizoku", "meaning": "繼續" },
    { "kanji": "維持", "kana": "いじ", "romaji": "iji", "meaning": "維持" },
    { "kanji": "破棄", "kana": "はき", "romaji": "haki", "meaning": "破棄" },
    { "kanji": "創造", "kana": "そうぞう", "romaji": "souzou", "meaning": "創造" },
    { "kanji": "崩壊", "kana": "ほうかい", "romaji": "houkai", "meaning": "崩壞" },
    { "kanji": "誕生", "kana": "たんじょう", "romaji": "tanjou", "meaning": "誕生" },
    { "kanji": "消滅", "kana": "しょうめつ", "romaji": "shoumetsu", "meaning": "消滅" },

    // === 351 - 400: 抽象概念、勝利與終局篇 ===
    { "kanji": "理想", "kana": "りそう", "romaji": "risou", "meaning": "理想" },
    { "kanji": "現実", "kana": "げんじつ", "romaji": "genjitsu", "meaning": "現實" },
    { "kanji": "妄想", "kana": "もうそう", "romaji": "mousou", "meaning": "妄想" },
    { "kanji": "正解", "kana": "せいかい", "romaji": "seikai", "meaning": "正確答案" },
    { "kanji": "間違い", "kana": "まちがい", "romaji": "machigai", "meaning": "錯誤" },
    { "kanji": "成功", "kana": "せいこう", "romaji": "seikou", "meaning": "成功" },
    { "kanji": "失敗", "kana": "しっぱい", "romaji": "shippai", "meaning": "失敗" },
    { "kanji": "挑戦", "kana": "ちょうせん", "romaji": "chousen", "meaning": "挑戰" },
    { "kanji": "旅人", "kana": "たびびと", "romaji": "tabibito", "meaning": "旅人" },
    { "kanji": "王者", "kana": "おうじゃ", "romaji": "ouja", "meaning": "王者" },
    { "kanji": "頂点", "kana": "ちょうてん", "romaji": "chouten", "meaning": "頂點" },
    { "kanji": "栄光", "kana": "えいこう", "romaji": "eikou", "meaning": "榮光" },
    { "kanji": "天国", "kana": "てんごく", "romaji": "tengoku", "meaning": "天國" },
    { "kanji": "地獄", "kana": "じごく", "romaji": "jigoku", "meaning": "地獄" },
    { "kanji": "光栄", "kana": "こうえい", "romaji": "kouei", "meaning": "光榮" },
    { "kanji": "最高", "kana": "さいこう", "romaji": "saikou", "meaning": "最高" },
    { "kanji": "最後", "kana": "さいご", "romaji": "saigo", "meaning": "最後" },
    { "kanji": "概念", "kana": "がいねん", "romaji": "gainen", "meaning": "概念" },
    { "kanji": "定義", "kana": "ていぎ", "romaji": "teigi", "meaning": "定義" },
    { "kanji": "論理", "kana": "ろんり", "romaji": "ronri", "meaning": "邏輯" },
    { "kanji": "矛盾", "kana": "むじゅん", "romaji": "mujun", "meaning": "矛盾" },
    { "kanji": "核心", "kana": "かくしん", "romaji": "kakushin", "meaning": "核心" },
    { "kanji": "極限", "kana": "げんかい", "romaji": "genkai", "meaning": "極限" },
    { "kanji": "終局", "kana": "しゅうきょく", "romaji": "shuukyoku", "meaning": "終局、結局" },
    { "kanji": "大結局", "kana": "だいけっきょく", "romaji": "daikekkyoku", "meaning": "大結局" },
    { "kanji": "迷宮", "kana": "めいきゅう", "romaji": "meikyuu", "meaning": "迷宮" },
    { "kanji": "宿命", "kana": "しゅくめい", "romaji": "shukumei", "meaning": "宿命" },
    { "kanji": "王道", "kana": "おうどう", "romaji": "oudou", "meaning": "王道" },
    { "kanji": "邪道", "kana": "じゃどう", "romaji": "jadou", "meaning": "邪道" },
    { "kanji": "覇者", "kana": "はしゃ", "romaji": "hasha", "meaning": "霸者" },
    { "kanji": "敗者", "kana": "はいしゃ", "romaji": "haisha", "meaning": "敗者" },
    { "kanji": "勝者", "kana": "しょうしゃ", "romaji": "shousha", "meaning": "勝者" },
    { "kanji": "凱旋", "kana": "がいせん", "romaji": "gaisen", "meaning": "凱旋" },
    { "kanji": "祝祭", "kana": "しゅくさい", "romaji": "shuksai", "meaning": "祝祭、慶典" },
    { "kanji": "儀式", "kana": "ぎしき", "romaji": "gishiki", "meaning": "儀式" },
    { "kanji": "生還", "kana": "せいかん", "romaji": "seikan", "meaning": "生還" },
    { "kanji": "全滅", "kana": "ぜんめつ", "romaji": "zenmetsu", "meaning": "全滅" },
    { "kanji": "降伏", "kana": "こうふく", "romaji": "koufuku", "meaning": "投降" },
    { "kanji": "抵抗", "kana": "ていこう", "romaji": "teikou", "meaning": "抵抗" },
    { "kanji": "革命", "kana": "かくめい", "romaji": "kakumei", "meaning": "革命" },
    { "kanji": "秩序", "kana": "ちつじょ", "romaji": "chitsujo", "meaning": "秩序" },
    { "kanji": "混沌", "kana": "こんとん", "romaji": "konton", "meaning": "混沌" },
    { "kanji": "崩御", "kana": "ほうぎょ", "romaji": "hougyo", "meaning": "駕崩" },
    { "kanji": "新星", "kana": "しんせい", "romaji": "shinsei", "meaning": "新星" },
    { "kanji": "巨星", "kana": "きょせい", "romaji": "kyosei", "meaning": "巨星" },
    { "kanji": "神聖", "kana": "しんせい", "romaji": "shinsei", "meaning": "神聖" },
    { "kanji": "暗黒", "kana": "あんこく", "romaji": "ankoku", "meaning": "暗黑" },
    { "kanji": "深淵", "kana": "しんえん", "romaji": "shinen", "meaning": "深淵" },
    { "kanji": "彼方", "kana": "かなた", "romaji": "kanata", "meaning": "彼方、遠方" },
    { "kanji": "境界", "kana": "きょうかい", "romaji": "kyoukai", "meaning": "境界、邊界" },

    // === 401 - 500: 日常與校園生活篇 (校園番、青春高頻詞) ===
    { "kanji": "学校", "kana": "がっこう", "romaji": "gakkou", "meaning": "學校" },
    { "kanji": "教室", "kana": "きょうしつ", "romaji": "kyoushitsu", "meaning": "教室" },
    { "kanji": "制服", "kana": "せいふく", "romaji": "seifuku", "meaning": "制服" },
    { "kanji": "青春", "kana": "せいしゅん", "romaji": "seishun", "meaning": "青春" },
    { "kanji": "友達", "kana": "ともだち", "romaji": "tomodachi", "meaning": "朋友" },
    { "kanji": "仲間", "kana": "なかま", "romaji": "nakama", "meaning": "夥伴" },
    { "kanji": "先生", "kana": "せんせい", "romaji": "sensei", "meaning": "老師" },
    { "kanji": "先輩", "kana": "せんぱい", "romaji": "senpai", "meaning": "學長、前輩" },
    { "kanji": "後輩", "kana": "こうはい", "romaji": "kouhai", "meaning": "學弟妹、後輩" },
    { "kanji": "同級生", "kana": "どうきゅうせい", "romaji": "doukyuusei", "meaning": "同班同學" },
    { "kanji": "放課後", "kana": "ほうかご", "romaji": "houkago", "meaning": "放學後" },
    { "kanji": "部活", "kana": "ぶかつ", "romaji": "bukatsu", "meaning": "社團活動" },
    { "kanji": "夕暮れ", "kana": "ゆうぐれ", "romaji": "yuugure", "meaning": "黃昏、傍晚" },
    { "kanji": "机", "kana": "つくえ", "romaji": "tsukue", "meaning": "桌子" },
    { "kanji": "椅子", "kana": "いす", "romaji": "isu", "meaning": "椅子" },
    { "kanji": "黑板", "kana": "こくばん", "romaji": "kokuban", "meaning": "黑板" },
    { "kanji": "教科書", "kana": "きょうかしょ", "romaji": "kyoukasho", "meaning": "教科書" },
    { "kanji": "宿題", "kana": "しゅくだい", "romaji": "shukudai", "meaning": "作業" },
    { "kanji": "試験", "kana": "しけん", "romaji": "shiken", "meaning": "考試" },
    { "kanji": "廊下", "kana": "ろうか", "romaji": "rouka", "meaning": "走廊" },
    { "kanji": "屋上", "kana": "おくじょう", "romaji": "okujou", "meaning": "頂樓" },
    { "kanji": "校庭", "kana": "こうてい", "romaji": "koutei", "meaning": "操場" },
    { "kanji": "体育館", "kana": "たいいくかん", "romaji": "taiikukan", "meaning": "體育館" },
    { "kanji": "文化祭", "kana": "ぶんかさい", "romaji": "bunkasai", "meaning": "文化祭" },
    { "kanji": "体育祭", "kana": "たいいくさい", "romaji": "taiikusai", "meaning": "運動會" },
    { "kanji": "夏休み", "kana": "なつやすみ", "romaji": "natsuyasumi", "meaning": "暑假" },
    { "kanji": "冬休み", "kana": "ふゆやすみ", "romaji": "fuyuyasumi", "meaning": "寒假" },
    { "kanji": "春休み", "kana": "はるやすみ", "romaji": "haruyasumi", "meaning": "春假" },
    { "kanji": "卒業", "kana": "そつぎょう", "romaji": "sotsugyou", "meaning": "畢業" },
    { "kanji": "入学", "kana": "にゅうがく", "romaji": "nyuugaku", "meaning": "入學" },
    { "kanji": "通学路", "kana": "つうがくろ", "romaji": "tsuugakuro", "meaning": "上學路" },
    { "kanji": "弁当", "kana": "べんとう", "romaji": "bentou", "meaning": "便當" },
    { "kanji": "購買", "kana": "こうばい", "romaji": "koubai", "meaning": "福利社" },
    { "kanji": "自転車", "kana": "じてんしゃ", "romaji": "jitensha", "meaning": "腳踏車" },
    { "kanji": "日常", "kana": "にちじょう", "romaji": "nichijou", "meaning": "日常" },
    { "kanji": "平凡", "kana": "へいぼん", "romaji": "heibon", "meaning": "平凡" },
    { "kanji": "秘密", "kana": "ひみつ", "romaji": "himitsu", "meaning": "秘密" },
    { "kanji": "噂", "kana": "うわさ", "romaji": "uwasa", "meaning": "傳聞、八卦" },
    { "kanji": "誤解", "kana": "ごかい", "romaji": "gokai", "meaning": "誤會" },
    { "kanji": "仲直り", "kana": "なかなおり", "romaji": "nakanaori", "meaning": "和好" },
    { "kanji": "日記", "kana": "にっき", "romaji": "nikki", "meaning": "日記" },
    { "kanji": "笑顔", "kana": "えがお", "romaji": "egao", "meaning": "笑容" },
    { "kanji": "喧嘩", "kana": "けんか", "romaji": "kenka", "meaning": "吵架" },
    { "kanji": "涙", "kana": "なみだ", "romaji": "namida", "meaning": "淚水" },
    { "kanji": "感動", "kana": "かんどう", "romaji": "kandou", "meaning": "感動" },
    { "kanji": "日常茶飯事", "kana": "にちじょうさはんじ", "romaji": "nichijousahanji", "meaning": "家常便飯" },
    { "kanji": "思い出", "kana": "おもいで", "romaji": "omoide", "meaning": "回憶" },
    { "kanji": "記憶", "kana": "きおく", "romaji": "kioku", "meaning": "記憶" },
    { "kanji": "未来", "kana": "みらい", "romaji": "mirai", "meaning": "未來" },
    { "kanji": "約束", "kana": "やくそく", "romaji": "yakusoku", "meaning": "約定" },

    // === 501 - 600: 異世界、奇幻與魔法篇 (輕小說、刀劍、芙莉蓮核心詞) ===
    { "kanji": "異世界", "kana": "いせかい", "romaji": "isekai", "meaning": "異世界" },
    { "kanji": "転生", "kana": "てんせい", "romaji": "tensei", "meaning": "轉生" },
    { "kanji": "召喚", "kana": "しょうかん", "romaji": "shoukan", "meaning": "召喚" },
    { "kanji": "勇者", "kana": "ゆうしゃ", "romaji": "yuusha", "meaning": "勇者" },
    { "kanji": "魔王", "kana": "まおう", "romaji": "maou", "meaning": "魔王" },
    { "kanji": "エルフ", "kana": "えるふ", "romaji": "erufu", "meaning": "精靈 (Elf)" },
    { "kanji": "ドワーフ", "kana": "どわーふ", "romaji": "dowaーfu", "meaning": "矮人 (Dwarf)" },
    { "kanji": "魔法使い", "kana": "まほうつかい", "romaji": "mahoutskai", "meaning": "魔法使" },
    { "kanji": "魔導書", "kana": "まどうしょ", "romaji": "madousho", "meaning": "魔導書" },
    { "kanji": "杖", "kana": "つえ", "romaji": "tsue", "meaning": "法杖" },
    { "kanji": "剣", "kana": "けん", "romaji": "ken", "meaning": "劍" },
    { "kanji": "盾", "kana": "たて", "romaji": "tate", "meaning": "盾牌" },
    { "kanji": "聖剣", "kana": "せいけん", "romaji": "seiken", "meaning": "聖劍" },
    { "kanji": "魔剣", "kana": "まけん", "romaji": "maken", "meaning": "魔劍" },
    { "kanji": "迷宮", "kana": "ダンジョン", "romaji": "danjon", "meaning": "地下城、迷宮" },
    { "kanji": "冒険者", "kana": "ぼうけんしゃ", "romaji": "boukensha", "meaning": "冒險者" },
    { "kanji": "ギルド", "kana": "ぎるど", "romaji": "girudo", "meaning": "公會" },
    { "kanji": "クエスト", "kana": "くえすと", "romaji": "kuesuto", "meaning": "任務 (Quest)" },
    { "kanji": "討伐", "kana": "とうばつ", "romaji": "toubatsu", "meaning": "討伐" },
    { "kanji": "魔物", "kana": "まもの", "romaji": "mamono", "meaning": "魔物" },
    { "kanji": "ドラゴン", "kana": "どらごん", "romaji": "doragon", "meaning": "巨龍" },
    { "kanji": "幻獣", "kana": "げんじゅう", "romaji": "genjuu", "meaning": "幻獸" },
    { "kanji": "妖精", "kana": "ようせい", "romaji": "yousei", "meaning": "妖精、精靈" },
    { "kanji": "精霊", "kana": "せいれい", "romaji": "seirei", "meaning": "精靈" },
    { "kanji": "呪文", "kana": "じゅもん", "romaji": "jumon", "meaning": "咒語" },
    { "kanji": "詠唱", "kana": "えいしょう", "romaji": "eishou", "meaning": "詠唱" },
    { "kanji": "魔力", "kana": "まりょく", "romaji": "maryoku", "meaning": "魔力" },
    { "kanji": "賢者", "kana": "けんじゃ", "romaji": "kenja", "meaning": "賢者" },
    { "kanji": "葬送", "kana": "そうそう", "romaji": "sousou", "meaning": "葬送 (葬送的芙莉蓮)" },
    { "kanji": "旅路", "kana": "たびじ", "romaji": "tabiji", "meaning": "旅途" },
    { "kanji": "遺品", "kana": "いひん", "romaji": "ihin", "meaning": "遺物" },
    { "kanji": "追憶", "kana": "ついおく", "romaji": "tsuioku", "meaning": "追憶" },
    { "kanji": "不老不死", "kana": "ふろうふし", "romaji": "furoufushi", "meaning": "不老不死" },
    { "kanji": "長壽", "kana": "ちょうじゅ", "romaji": "chouju", "meaning": "長壽" },
    { "kanji": "人間", "kana": "にんげん", "romaji": "ningen", "meaning": "人類" },
    { "kanji": "魔族", "kana": "まぞく", "romaji": "mazoku", "meaning": "魔族" },
    { "kanji": "結界", "kana": "けっかい", "romaji": "kekkai", "meaning": "結界" },
    { "kanji": "封印", "kana": "ふういん", "romaji": "fuuin", "meaning": "封印" },
    { "kanji": "解呪", "kana": "かいじゅ", "romaji": "kaiju", "meaning": "解開詛咒" },
    { "kanji": "錬金術師", "kana": "れんきんじゅつし", "romaji": "renkinjutsushi", "meaning": "鍊金術師" },
    { "kanji": "遺跡", "kana": "いせき", "romaji": "iseki", "meaning": "遺跡" },
    { "kanji": "神殿", "kana": "しんでん", "romaji": "shinden", "meaning": "神殿" },
    { "kanji": "王國", "kana": "おうこく", "romaji": "oukoku", "meaning": "王國" },
    { "kanji": "帝國", "kana": "ていこく", "romaji": "teikoku", "meaning": "帝國" },
    { "kanji": "騎士團", "kana": "きしだん", "romaji": "kishidan", "meaning": "騎士團" },
    { "kanji": "傭兵", "kana": "ようへい", "romaji": "youhei", "meaning": "傭兵" },
    { "kanji": "財寶", "kana": "ざいほう", "romaji": "zaihou", "meaning": "財寶" },
    { "kanji": "罠", "kana": "わな", "romaji": "wana", "meaning": "陷阱" },
    { "kanji": "ステータス", "kana": "すてーたす", "romaji": "suteーtasu", "meaning": "狀態欄 (Status)" },
    { "kanji": "スキル", "kana": "すきる", "romaji": "sukiru", "meaning": "技能 (Skill)" },

    // === 601 - 700: 情感動詞與擬聲擬態詞篇 (J-POP 歌詞超高頻) ===
    { "kanji": "煌めく", "kana": "きらめく", "romaji": "kirameku", "meaning": "閃耀" },
    { "kanji": "輝く", "kana": "かがやく", "romaji": "kagayaku", "meaning": "發光" },
    { "kanji": "揺れる", "kana": "ゆれる", "romaji": "yureru", "meaning": "搖擺" },
    { "kanji": "触れる", "kana": "ふれる", "romaji": "fureru", "meaning": "觸碰" },
    { "kanji": "重ねる", "kana": "かさねる", "romaji": "kasaneru", "meaning": "重疊" },
    { "kanji": "零れる", "kana": "こぼれる", "romaji": "koboreru", "meaning": "溢出、灑落" },
    { "kanji": "溢れる", "kana": "あふれる", "romaji": "afureru", "meaning": "充滿、溢出" },
    { "kanji": "伝える", "kana": "つたえる", "romaji": "tsutaeru", "meaning": "傳達" },
    { "kanji": "届く", "kana": "とどく", "romaji": "todoku", "meaning": "傳到、抵達" },
    { "kanji": "叶う", "kana": "かなう", "romaji": "kanau", "meaning": "實現" },
    { "kanji": "叫ぶ", "kana": "さけぶ", "romaji": "sakebu", "meaning": "吶喊" },
    { "kanji": "嘆く", "kana": "なげく", "romaji": "nageku", "meaning": "嘆息、悲嘆" },
    { "kanji": "狂う", "kana": "くるう", "romaji": "kuruu", "meaning": "發狂" },
    { "kanji": "愛する", "kana": "あいする", "romaji": "aisuru", "meaning": "愛" },
    { "kanji": "恋する", "kana": "こいする", "romaji": "koisuru", "meaning": "戀愛" },
    { "kanji": "信じる", "kana": "しんじる", "romaji": "shinjiru", "meaning": "相信" },
    { "kanji": "疑う", "kana": "うたがう", "romaji": "utagau", "meaning": "懷疑" },
    { "kanji": "許す", "kana": "ゆるす", "romaji": "yurusu", "meaning": "原諒" },
    { "kanji": "憎む", "kana": "にくむ", "romaji": "nikumu", "meaning": "憎恨" },
    { "kanji": "傷つく", "kana": "きずつく", "romaji": "kizutsuku", "meaning": "受傷" },
    { "kanji": "癒やす", "kana": "いやす", "romaji": "iyasu", "meaning": "療癒" },
    { "kanji": "包む", "kana": "つつむ", "romaji": "tsutsumu", "meaning": "包覆" },
    { "kanji": "奪う", "kana": "うばう", "romaji": "ubau", "meaning": "奪走" },
    { "kanji": "守る", "kana": "まもる", "romaji": "mamoru", "meaning": "守護" },
    { "kanji": "壊す", "kana": "こわす", "romaji": "kowasu", "meaning": "破壞" },
    { "kanji": "きらきら", "kana": "きらきら", "romaji": "kirakira", "meaning": "閃亮地" },
    { "kanji": "うるうる", "kana": "うるうる", "romaji": "uruuru", "meaning": "淚眼汪汪地" },
    { "kanji": "どきどき", "kana": "どきどき", "romaji": "dokidoki", "meaning": "心跳雀躍地" },
    { "kanji": "わくわく", "kana": "わくわく", "romaji": "wakuwaku", "meaning": "興奮期待地" },
    { "kanji": "ハラハラ", "kana": "はらはら", "romaji": "harahara", "meaning": "捏一把冷汗地" },
    { "kanji": "じっと", "kana": "じっと", "romaji": "jitto", "meaning": "凝視、一動也不動" },
    { "kanji": "そっと", "kana": "そっと", "romaji": "sotto", "meaning": "輕輕地、悄悄地" },
    { "kanji": "ずっと", "kana": "ずっと", "romaji": "zutto", "meaning": "一直" },
    { "kanji": "きっと", "kana": "きっと", "romaji": "kitto", "meaning": "一定" },
    { "kanji": "もっと", "kana": "もっと", "romaji": "motto", "meaning": "更加" },
    { "kanji": "ふわり", "kana": "ふわり", "romaji": "fuwari", "meaning": "輕飄飄地" },
    { "kanji": "ゆらゆら", "kana": "ゆらゆら", "romaji": "yurayura", "meaning": "搖搖晃晃地" },
    { "kanji": "ひらひら", "kana": "ひらひら", "romaji": "hirahira", "meaning": "翩翩起舞地、飄落" },
    { "kanji": "さらさら", "kana": "さらさら", "romaji": "sarasara", "meaning": "沙沙作響、流暢地" },
    { "kanji": "うるさく", "kana": "うるさく", "romaji": "urusaku", "meaning": "吵鬧地" },
    { "kanji": "静かに", "kana": "しずかに", "romaji": "shizukani", "meaning": "安靜地" },
    { "kanji": "激しく", "kana": "はげしく", "romaji": "hageshiku", "meaning": "劇烈地" },
    { "kanji": "優しく", "kana": "やさしく", "romaji": "yasashiku", "meaning": "溫柔地" },
    { "kanji": "切なく", "kana": "せつなく", "romaji": "setsunaku", "meaning": "苦悶難過地" },
    { "kanji": "虚しく", "kana": "むなしく", "romaji": "munashiku", "meaning": "空虛地" },
    { "kanji": "寂しく", "kana": "さびしく", "romaji": "sabishiku", "meaning": "寂寞地" },
    { "kanji": "懐かしく", "kana": "なつかしく", "romaji": "natsukashiku", "meaning": "懷念地" },
    { "kanji": "新しく", "kana": "あたらしく", "romaji": "atarashiku", "meaning": "全新地" },
    { "kanji": "古く", "kana": "ふるく", "romaji": "furuku", "meaning": "古老地" },
    { "kanji": "美しく", "kana": "うつくしく", "romaji": "utsukushiku", "meaning": "美麗地" },

    // === 701 - 800: 中二病、宿命與暗黑美學篇 (東京喰種、鏈鋸人、地獄樂) ===
    { "kanji": "赫眼", "kana": "かくがん", "romaji": "kakugan", "meaning": "赫眼 (東京喰種)" },
    { "kanji": "喰種", "kana": "グール", "romaji": "guーru", "meaning": "喰種" },
    { "kanji": "悲劇", "kana": "ひげき", "romaji": "higeki", "meaning": "悲劇" },
    { "kanji": "錯乱", "kana": "さくらん", "romaji": "sakuran", "meaning": "錯亂" },
    { "kanji": "狂気", "kana": "きょうき", "romaji": "kyouki", "meaning": "狂氣" },
    { "kanji": "悪魔", "kana": "あくま", "romaji": "akuma", "meaning": "惡魔 (鏈鋸人)" },
    { "kanji": "契約", "kana": "けいやく", "romaji": "keiyaku", "meaning": "契約" },
    { "kanji": "代償", "kana": "だいしょう", "romaji": "daishou", "meaning": "代價" },
    { "kanji": "心臓", "kana": "しんぞう", "romaji": "shinzou", "meaning": "心臟" },
    { "kanji": "血沫", "kana": "ちしぶき", "romaji": "chishibuki", "meaning": "血濺" },
    { "kanji": "地獄", "kana": "じごく", "romaji": "jigoku", "meaning": "地獄" },
    { "kanji": "極楽", "kana": "ごくらく", "romaji": "gokuraku", "meaning": "極樂 (地獄樂)" },
    { "kanji": "忍び", "kana": "しのび", "romaji": "shinobi", "meaning": "忍者" },
    { "kanji": "死罪", "kana": "しざい", "romaji": "shizai", "meaning": "死罪" },
    { "kanji": "執行人", "kana": "しっこうにん", "romaji": "shikkounin", "meaning": "執行人" },
    { "kanji": "不老長寿", "kana": "ふろうちょうじゅ", "romaji": "furouchouju", "meaning": "不老長壽" },
    { "kanji": "神仙", "kana": "しんせん", "romaji": "shinsen", "meaning": "神仙" },
    { "kanji": "怪異", "kana": "かいい", "romaji": "kaii", "meaning": "怪異 (物語系列)" },
    { "kanji": "吸血鬼", "kana": "きゅうけつき", "romaji": "kyuuketsuki", "meaning": "吸血鬼" },
    { "kanji": "偽物", "kana": "にせもの", "romaji": "nisemono", "meaning": "偽物" },
    { "kanji": "本物", "kana": "ほんもの", "romaji": "honmono", "meaning": "真貨" },
    { "kanji": "怪盗", "kana": "かいとう", "romaji": "kaitou", "meaning": "怪盜" },
    { "kanji": "予告状", "kana": "よこくじょう", "romaji": "yokokujou", "meaning": "預告信" },
    { "kanji": "魔術", "kana": "まじゅつ", "romaji": "majutsu", "meaning": "魔術" },
    { "kanji": "幻想", "kana": "げんそう", "romaji": "gensou", "meaning": "幻想" },
    { "kanji": "禁忌", "kana": "きんき", "romaji": "kinki", "meaning": "禁忌" },
    { "kanji": "堕天使", "kana": "だてんし", "romaji": "datenshi", "meaning": "墮天使" },
    { "kanji": "審判", "kana": "しんぱん", "romaji": "shinpan", "meaning": "審判" },
    { "kanji": "煉獄", "kana": "れんごく", "romaji": "rengoku", "meaning": "煉獄" },
    { "kanji": "聖戦", "kana": "せいせん", "romaji": "seisen", "meaning": "聖戰" },
    { "kanji": "贖罪", "kana": "しょくざい", "romaji": "shokuzai", "meaning": "贖罪" },
    { "kanji": "孤高", "kana": "ここう", "romaji": "kokou", "meaning": "孤高" },
    { "kanji": "傲慢", "kana": "ごうまん", "romaji": "gouman", "meaning": "傲慢" },
    { "kanji": "憤怒", "kana": "ふんど", "romaji": "fundo", "meaning": "憤怒" },
    { "kanji": "嫉妬", "kana": "しっと", "romaji": "shitto", "meaning": "嫉妒" },
    { "kanji": "強欲", "kana": "ごうよく", "romaji": "gouyoku", "meaning": "貪婪" },
    { "kanji": "暴食", "kana": "ぼうしょく", "romaji": "boushoku", "meaning": "暴食" },
    { "kanji": "怠惰", "kana": "たいだ", "romaji": "taida", "meaning": "怠惰" },
    { "kanji": "色欲", "kana": "しきよく", "romaji": "shikiyoku", "meaning": "色慾" },
    { "kanji": "黒幕", "kana": "くろまく", "romaji": "kuromaku", "meaning": "幕後黑手" },
    { "kanji": "陰謀", "kana": "いんぼう", "romaji": "inbou", "meaning": "陰謀" },
    { "kanji": "裏切り", "kana": "うらぎり", "romaji": "uragiri", "meaning": "背叛" },
    { "kanji": "漆黒", "kana": "しっこく", "romaji": "shikkoku", "meaning": "漆黑" },
    { "kanji": "深紅", "kana": "しんく", "romaji": "shinku", "meaning": "深紅" },
    { "kanji": "白銀", "kana": "はくぎん", "romaji": "hakugin", "meaning": "白銀" },
    { "kanji": "黄金", "kana": "おうごん", "romaji": "ougon", "meaning": "黃金" },
    { "kanji": "虚無", "kana": "きょむ", "romaji": "kyomu", "meaning": "虛無" },
    { "kanji": "絶望", "kana": "ぜつぼう", "romaji": "zetsubou", "meaning": "絕望" },
    { "kanji": "覚悟", "kana": "かくご", "romaji": "kakugo", "meaning": "覺悟" },
    { "kanji": "因果", "kana": "いんが", "romaji": "inga", "meaning": "因果" },

    // === 801 - 900: 電玩、科幻與未來科技篇 (刀劍神域、賽博朋克) ===
    { "kanji": "電脳", "kana": "でんのう", "romaji": "dennou", "meaning": "電腦、網路" },
    { "kanji": "仮想現実", "kana": "かそうげんじつ", "romaji": "kasougenjitsu", "meaning": "虛擬實境" },
    { "kanji": "人工知能", "kana": "じんこうちのう", "romaji": "jinkouchinou", "meaning": "人工智慧" },
    { "kanji": "機械", "kana": "きかい", "romaji": "kikai", "meaning": "機械" },
    { "kanji": "鋼鉄", "kana": "こうてつ", "romaji": "koutetsu", "meaning": "鋼鐵" },
    { "kanji": "回路", "kana": "かいろ", "romaji": "kairo", "meaning": "電路、迴路" },
    { "kanji": "電波", "kana": "でんぱ", "romaji": "denpa", "meaning": "電波" },
    { "kanji": "同期", "kana": "どうき", "romaji": "douki", "meaning": "同步" },
    { "kanji": "接続", "kana": "せつぞく", "romaji": "setsuzoku", "meaning": "連接、線上" },
    { "kanji": "切断", "kana": "せつだん", "romaji": "setsudan", "meaning": "切斷、斷線" },
    { "kanji": "崩壊", "kana": "ほうかい", "romaji": "houkai", "meaning": "崩壞" },
    { "kanji": "再生", "kana": "さいせい", "romaji": "saisei", "meaning": "再生、播放" },
    { "kanji": "複製", "kana": "ふくせい", "romaji": "fukusei", "meaning": "複製" },
    { "kanji": "初期化", "kana": "しょきか", "romaji": "shokika", "meaning": "格式化、初始化" },
    { "kanji": "記憶媒体", "kana": "きおくばいたい", "romaji": "kiokubaitai", "meaning": "記憶媒體" },
    { "kanji": "暗号", "kana": "あんごう", "romaji": "angou", "meaning": "密碼、暗號" },
    { "kanji": "未来都市", "kana": "みらいとし", "romaji": "miraitoshi", "meaning": "未來都市" },
    { "kanji": "宇宙航行", "kana": "うちゅうこうこう", "romaji": "uchuukoukou", "meaning": "宇宙航行" },
    { "kanji": "新星", "kana": "しんせい", "romaji": "shinsei", "meaning": "新星" },
    { "kanji": "銀河系", "kana": "ぎんがけい", "romaji": "gingakei", "meaning": "銀河系" },
    { "kanji": "時空", "kana": "じくう", "romaji": "jikuu", "meaning": "時空" },
    { "kanji": "異次元", "kana": "いじげん", "romaji": "ijigen", "meaning": "異次元" },
    { "kanji": "並行世界", "kana": "へいこうせかい", "romaji": "heikousekai", "meaning": "平行世界" },
    { "kanji": "時間跳躍", "kana": "タイムリープ", "romaji": "taimuriーpu", "meaning": "時間跳躍 (Time Leap)" },
    { "kanji": "因果律", "kana": "いんがりつ", "romaji": "ingaritsu", "meaning": "因果律" },
    { "kanji": "最適化", "kana": "さいてきか", "romaji": "saitekika", "meaning": "最佳化" },
    { "kanji": "不具合", "kana": "ふぐあい", "romaji": "fuguai", "meaning": "Bug、故障" },
    { "kanji": "暴走", "kana": "ぼうそう", "romaji": "bousou", "meaning": "暴走、失控" },
    { "kanji": "修復", "kana": "しゅうふく", "romaji": "shuufuku", "meaning": "修復" },
    { "kanji": "電磁気", "kana": "でんじき", "romaji": "denjiki", "meaning": "電磁氣" },
    { "kanji": "高電壓", "kana": "こうでんあつ", "romaji": "koudenatsu", "meaning": "高電壓" },
    { "kanji": "光速", "kana": "こうそく", "romaji": "kousoku", "meaning": "光速" },
    { "kanji": "音速", "kana": "おんそく", "romaji": "onsoku", "meaning": "音速" },
    { "kanji": "衝擊波", "kana": "しょうげきは", "romaji": "shougekiha", "meaning": "衝擊波" },
    { "kanji": "粒子", "kana": "りゅうし", "romaji": "ryuushi", "meaning": "粒子" },
    { "kanji": "量子", "kana": "りょうし", "romaji": "ryoushi", "meaning": "量子" },
    { "kanji": "電導", "kana": "でんどう", "romaji": "dendou", "meaning": "電導" },
    { "kanji": "絶縁", "kana": "ぜつえん", "romaji": "zetsuen", "meaning": "絕緣、斷絕關係" },
    { "kanji": "結晶", "kana": "けっしょう", "romaji": "kesshou", "meaning": "結晶" },
    { "kanji": "流動", "kana": "りゅうどう", "romaji": "ryuudou", "meaning": "流動" },
    { "kanji": "凝縮", "kana": "ぎょうしゅく", "romaji": "gyoushuku", "meaning": "濃縮" },
    { "kanji": "昇華", "kana": "しょうか", "romaji": "shouka", "meaning": "昇華" },
    { "kanji": "破裂", "kana": "はれつ", "romaji": "haretsu", "meaning": "破裂" },
    { "kanji": "融合", "kana": "ゆうごう", "romaji": "yuugou", "meaning": "融合" },
    { "kanji": "分裂", "kana": "ぶんれつ", "romaji": "bunretsu", "meaning": "分裂" },
    { "kanji": "連鎖反応", "kana": "れんさはんのう", "romaji": "rensahannou", "meaning": "連鎖反應" },
    { "kanji": "臨界点", "kana": "りんかいてん", "romaji": "rinkaiten", "meaning": "臨界點" },
    { "kanji": "無限大", "kana": "むげんだい", "romaji": "mugendai", "meaning": "無限大" },
    { "kanji": "零度", "kana": "れいど", "romaji": "reido", "meaning": "零度" },
    { "kanji": "絶対零度", "kana": "ぜったいれいど", "romaji": "zettaireido", "meaning": "絕對零度" },

    // === 901 - 1000: 日K神曲完結、終焉與新篇章 ===
    { "kanji": "終焉", "kana": "しゅうえん", "romaji": "shuuen", "meaning": "終焉、迎向結局" },
    { "kanji": "大団円", "kana": "だいだんえん", "romaji": "daidanen", "meaning": "大團圓、完美結局" },
    { "kanji": "終幕", "kana": "しゅうまく", "romaji": "shuumaku", "meaning": "落幕" },
    { "kanji": "序幕", "kana": "じょまく", "romaji": "jomaku", "meaning": "序幕" },
    { "kanji": "新章", "kana": "しんしょう", "romaji": "shinshou", "meaning": "新篇章" },
    { "kanji": "奏鳴曲", "kana": "ソナタ", "romaji": "sonata", "meaning": "奏鳴曲 (Sonata)" },
    { "kanji": "小奏鳴曲", "kana": "ソナチネ", "romaji": "sonachine", "meaning": "小奏鳴曲" },
    { "kanji": "協奏曲", "kana": "コンチェルト", "romaji": "koncheruto", "meaning": "協奏曲" },
    { "kanji": "即興曲", "kana": "アンプロンプチュ", "romaji": "anporonpuchu", "meaning": "即興曲" },
    { "kanji": "練習曲", "kana": "エチュード", "romaji": "echuーdo", "meaning": "練習曲" },
    { "kanji": "夜想曲", "kana": "ノクターン", "romaji": "nokutaーn", "meaning": "夜想曲" },
    { "kanji": "交響詩", "kana": "こうきょうし", "romaji": "koukyoushi", "meaning": "交響詩" },
    { "kanji": "輪舞曲", "kana": "ロンド", "romaji": "rondo", "meaning": "輪舞曲" },
    { "kanji": "組曲", "kana": "くみきょく", "romaji": "kumikyoku", "meaning": "組曲" },
    { "kanji": "音の壁", "kana": "おのかべ", "romaji": "onokabe", "meaning": "音牆" },
    { "kanji": "残響散歌", "kana": "ざんきょうさんか", "romaji": "zankyousanka", "meaning": "殘響散歌" },
    { "kanji": "打上花火", "kana": "うちあげはなび", "romaji": "uchiagehanabi", "meaning": "打上花火" },
    { "kanji": "向日葵", "kana": "ひまわり", "romaji": "himawari", "meaning": "向日葵" },
    { "kanji": "青のすみか", "kana": "あおのすみか", "romaji": "aonosumika", "meaning": "青之居所 (咒術迴戰懷玉折玉)" },
    { "kanji": "アイドル", "kana": "あいどる", "romaji": "aidoru", "meaning": "偶像 (Idol)" },
    { "kanji": "最強", "kana": "さいきょう", "romaji": "saikyou", "meaning": "最強" },
    { "kanji": "無敵", "kana": "むてき", "romaji": "muteki", "meaning": "無敵" },
    { "kanji": "天才", "kana": "てんさい", "romaji": "tensai", "meaning": "天才" },
    { "kanji": "究極", "kana": "きゅうきょく", "romaji": "kyuukyoku", "meaning": "究極" },
    { "kanji": "一番", "kana": "いちばん", "romaji": "ichiban", "meaning": "第一、最..." },
    { "kanji": "特別", "kana": "とくべつ", "romaji": "tokubetsu", "meaning": "特別" },
    { "kanji": "唯一", "kana": "ゆいいつ", "romaji": "yuiitsu", "meaning": "唯一" },
    { "kanji": "絶対", "kana": "ぜったい", "romaji": "zettai", "meaning": "絕對" },
    { "kanji": "永遠", "kana": "えいえん", "romaji": "eien", "meaning": "永遠" },
    { "kanji": "無限", "kana": "むげん", "romaji": "mugen", "meaning": "無限" },
    { "kanji": "光芒", "kana": "こうぼう", "romaji": "koubou", "meaning": "光芒" },
    { "kanji": "一筋", "kana": "ひとすじ", "romaji": "hitosuji", "meaning": "一縷、專心致志" },
    { "kanji": "希望の光", "kana": "きぼうのひかり", "romaji": "kibounohikari", "meaning": "希望之光" },
    { "kanji": "一歩ずつ", "kana": "いっぽずつ", "romaji": "ippozutsu", "meaning": "一步一步地" },
    { "kanji": "足跡", "kana": "あしあと", "romaji": "ashiato", "meaning": "足跡" },
    { "kanji": "軌跡", "kana": "きせき", "romaji": "kiseki", "meaning": "軌跡" },
    { "kanji": "旅路", "kana": "たびじ", "romaji": "tabiji", "meaning": "旅途" },
    { "kanji": "故郷", "kana": "ふるさと", "romaji": "furusato", "meaning": "故鄉" },
    { "kanji": "再会", "kana": "さいかい", "romaji": "saikai", "meaning": "重逢" },
    { "kanji": "約束の地", "kana": "やくそくのち", "romaji": "yakusokunochi", "meaning": "約定之地" },
    { "kanji": "新天地", "kana": "しんてんち", "romaji": "shintenchi", "meaning": "新天地" },
    { "kanji": "夜明け前", "kana": "よあけまえ", "romaji": "yoakemae", "meaning": "黎明前夕" },
    { "kanji": "一番星", "kana": "いちばんぼし", "romaji": "ichibanboshi", "meaning": "第一顆亮起的星、啟明星" },
    { "kanji": "光輝く", "kana": "ひかりかがやく", "romaji": "hikarikagayaku", "meaning": "光芒萬丈" },
    { "kanji": "未来永劫", "kana": "みらいえいごう", "romaji": "miraieigou", "meaning": "未來永劫、直到永遠" },
    { "kanji": "不滅", "kana": "ふめつ", "romaji": "fumetsu", "meaning": "不滅" },
    { "kanji": "不死鳥", "kana": "フェニックス", "romaji": "fenikkusu", "meaning": "不死鳥、鳳凰" },
    { "kanji": "神話の果て", "kana": "しんわのはて", "romaji": "shinwanohate", "meaning": "神話的終點" },
    { "kanji": "最高潮", "kana": "クライマックス", "romaji": "kuraimakkusu", "meaning": "高潮、Climax" },
    { "kanji": "完結", "kana": "かんけつ", "romaji": "kanketsu", "meaning": "完結" },

    // === 1001 - 1100: 2000~2010 平成盛世經典 J-POP 核心篇 ===
    { "kanji": "望遠鏡", "kana": "ぼうえんきょう", "romaji": "bouenkyou", "meaning": "望遠鏡 (BUMP OF CHICKEN - 天体観測)" },
    { "kanji": "踏切", "kana": "ふみきり", "romaji": "fumikiri", "meaning": "鐵路平交道 (天体観測 / 經典街景)" },
    { "kanji": "粉雪", "kana": "こなゆき", "romaji": "konayuki", "meaning": "粉雪 (レミオロメン - 粉雪)" },
    { "kanji": "改札口", "kana": "かいさつぐち", "romaji": "kaisatsuguchi", "meaning": "剪票口 (スキマスイッチ - 奏)" },
    { "kanji": "木枯らし", "kana": "こがらし", "romaji": "kogarashi", "meaning": "初冬寒風 (中島美嘉 - 雪の華)" },
    { "kanji": "薄紅色", "kana": "うすべにいろ", "romaji": "usubeniiro", "meaning": "淡粉紅色 (一青窈 - ハナミズキ)" },
    { "kanji": "百年", "kana": "ひゃくねん", "romaji": "hyaknen", "meaning": "百年 (願你與心愛的人百年好合)" },
    { "kanji": "幻", "kana": "まぼろし", "romaji": "maboroshi", "meaning": "幻影、虛幻 (柴咲コウ - かたちあるもの)" },
    { "kanji": "片道切符", "kana": "かたみちきっぷ", "romaji": "katamichikippu", "meaning": "單程車票 (流行歌詞常見意象)" },
    { "kanji": "飛行機雲", "kana": "ひこうきぐも", "romaji": "hikoukigumo", "meaning": "飛機雲 (荒井由実 / ACG抒情曲)" },
    { "kanji": "三日月", "kana": "みかづき", "romaji": "mikazuki", "meaning": "弦月、三日月 (絢香 - 三日月)" },
    { "kanji": "交わす", "kana": "かわす", "romaji": "kawasu", "meaning": "交換 (交織言語或眼神)" },
    { "kanji": "幾千", "kana": "いくせん", "romaji": "ikusen", "meaning": "成千上萬 (創聖的大天使/抒情副歌)" },
    { "kanji": "愛言葉", "kana": "あいことば", "romaji": "aikotoba", "meaning": "暗號、愛的密語 (Vocaloid 經典曲)" },
    { "kanji": "溶ける", "kana": "tokeru", "romaji": "tokeru", "meaning": "融化 (supercell - メルト)" },
    { "kanji": "傘", "kana": "かさ", "romaji": "kasa", "meaning": "雨傘 (忘記帶傘的雨天心境)" },
    { "kanji": "お姫様", "kana": "おひめさま", "romaji": "ohimesama", "meaning": "公主 (World is Mine 歌詞)" },
    { "kanji": "我がまま", "kana": "わがまま", "romaji": "wagamama", "meaning": "任性" },
    { "kanji": "一瞥", "kana": "いちべつ", "romaji": "ichbetsu", "meaning": "瞧一眼、一瞥" },
    { "kanji": "不器用", "kana": "ぶきよう", "romaji": "bukiyou", "meaning": "笨拙的 (形容戀愛不擅表達)" },
    { "kanji": "巡り合う", "kana": "めぐりあう", "romaji": "meguriau", "meaning": "奇蹟般的重逢" },
    { "kanji": "何十年", "kana": "なんじゅうねん", "romaji": "nanjuunen", "meaning": "幾十年 (GReeeeN - キセキ)" },
    { "kanji": "明日晴れ", "kana": "あしたはれ", "romaji": "ashitahare", "meaning": "明天放晴 (桑田佳祐經典之作)" },
    { "kanji": "蕾", "kana": "つぼみ", "romaji": "tsubomi", "meaning": "花蕾 (コブクロ - 蕾)" },
    { "kanji": "泥だらけ", "kana": "どろだらけ", "romaji": "doradarake", "meaning": "滿是泥濘 (青春熱血奮鬥詞)" },
    { "kanji": "遠回り", "kana": "とおまわり", "romaji": "toomawari", "meaning": "繞遠路 (放學路的戀愛酸甜)" },
    { "kanji": "高鳴る", "kana": "たかなる", "romaji": "takanaru", "meaning": "激動、雀躍 (心跳加速)" },
    { "kanji": "面影", "kana": "おもかげ", "romaji": "omokage", "meaning": "記憶中的身影" },
    { "kanji": "茜空", "kana": "あかねぞら", "romaji": "akanezora", "meaning": "染成暗紅色的晚霞天空" },
    { "kanji": "泡沫", "kana": "うたかた", "romaji": "utakata", "meaning": "泡沫、短暫如夢" },
    { "kanji": "帰り道", "kana": "かえりみち", "romaji": "kaerimichi", "meaning": "回家的路" },
    { "kanji": "一番星", "kana": "いちばんぼし", "romaji": "ichibanboshi", "meaning": "夜空中第一顆亮起的星" },
    { "kanji": "君色", "kana": "きみいろ", "romaji": "kimiiro", "meaning": "屬於你的顏色" },
    { "kanji": "落書き", "kana": "らくがき", "romaji": "rakugaki", "meaning": "塗鴉 (課本或課桌上的青春記憶)" },
    { "kanji": "教科書", "kana": "きょうかしょ", "romaji": "kyoukasho", "meaning": "教科書" },
    { "kanji": "木星", "kana": "もくせい", "romaji": "mokusei", "meaning": "木星 (平原綾香 - Jupiter)" },
    { "kanji": "旅人", "kana": "たびびと", "romaji": "tabibito", "meaning": "旅人" },
    { "kanji": "桜並木", "kana": "さくらなみき", "romaji": "sakuranamiki", "meaning": "櫻花樹道" },
    { "kanji": "陽のあたる", "kana": "ひのあたる", "romaji": "hinoataru", "meaning": "陽光照耀的" },
    { "kanji": "桜坂", "kana": "さくらざか", "romaji": "sakurazaka", "meaning": "櫻花坡道 (福山雅治 - 桜坂)" },
    { "kanji": "雪の跡", "kana": "ゆきのあと", "romaji": "yukinoto", "meaning": "雪的痕跡" },
    { "kanji": "初雪", "kana": "はつゆき", "romaji": "hatsuyuki", "meaning": "初雪" },
    { "kanji": "木漏れ日", "kana": "こもれび", "romaji": "komorebi", "meaning": "樹蔭間漏出的陽光" },
    { "kanji": "千の風", "kana": "せんのかぜ", "romaji": "sennokaze", "meaning": "千陣風 (化為千風)" },
    { "kanji": "千の夜", "kana": "せんのよる", "romaji": "sennoyoru", "meaning": "千個夜晚 (Aqua Timez)" },
    { "kanji": "虹色", "kana": "にじいろ", "romaji": "nijiiro", "meaning": "彩虹色" },
    { "kanji": "明日への", "kana": "あしたへの", "romaji": "ashitaheno", "meaning": "邁向明天的" },
    { "kanji": "風になって", "kana": "かぜになって", "romaji": "kazeninate", "meaning": "化作風" },
    { "kanji": "手をつなぐ", "kana": "てをつなぐ", "romaji": "teotsunagu", "meaning": "牽手" },
    { "kanji": "抱きしめる", "kana": "だきしめる", "romaji": "dakishimeru", "meaning": "緊抱" },

    // === 1101 - 1200: 2011~2020 現代神曲、白金期與白熱化 J-POP 篇 ===
    { "kanji": "匂い", "kana": "におい", "romaji": "nioi", "meaning": "氣味 (米津玄師 - Lemon：苦澀檸檬香)" },
    { "kanji": "果実", "kana": "かじつ", "romaji": "kajitsu", "meaning": "果實 (切開的切片果實)" },
    { "kanji": "未だに", "kana": "いまだに", "romaji": "imadani", "meaning": "直到如今、依然" },
    { "kanji": "切り分ける", "kana": "きりわける", "romaji": "kiriwakeru", "meaning": "切開、切分" },
    { "kanji": "麦わら帽子", "kana": "むぎわらぼうし", "romaji": "mugiwaraboushi", "meaning": "草帽 (あいみょん - マリーゴールド)" },
    { "kanji": "揺るぎない", "kana": "ゆるぎない", "romaji": "yuruginai", "meaning": "堅定不移的" },
    { "kanji": "グッバイ", "kana": "ぐっばい", "romaji": "gubbai", "meaning": "再見 (Official髭男dism - Pretender)" },
    { "kanji": "詐欺師", "kana": "さぎし", "romaji": "sagishi", "meaning": "詐欺師 (Pretender 歌詞意象)" },
    { "kanji": "綺麗だ", "kana": "きれいだ", "romaji": "kireida", "meaning": "真漂亮啊" },
    { "kanji": "感情", "kana": "かんじょう", "romaji": "kanjou", "meaning": "感情" },
    { "kanji": "前前前世", "kana": "ぜんぜんぜんせ", "romaji": "zenzenzense", "meaning": "前前前世 (RADWIMPS - 你的名字)" },
    { "kanji": "銀河", "kana": "ぎんが", "romaji": "ginga", "meaning": "銀河" },
    { "kanji": "何光年", "kana": "なんこうねん", "romaji": "nankounen", "meaning": "幾光年 (跨越時空的思念)" },
    { "kanji": "白日", "kana": "はくじつ", "romaji": "hakujitsu", "meaning": "白日、青天白日 (King Gnu - 白日)" },
    { "kanji": "戻れない", "kana": "もどれない", "romaji": "modorenai", "meaning": "無法回去 (成年人的遺憾心境)" },
    { "kanji": "足跡", "kana": "あしあと", "romaji": "ashiato", "meaning": "足跡、腳印" },
    { "kanji": "林檎", "kana": "りんご", "romaji": "ringo", "meaning": "蘋果 (椎名林檎 / 東京事變經典意象)" },
    { "kanji": "始発列車", "kana": "しはつれっしゃ", "romaji": "shihatsureshsha", "meaning": "首班列車 (深夜或清晨的都市感)" },
    { "kanji": "東京タワー", "kana": "とうきょうたわー", "romaji": "toukyoutawaー", "meaning": "東京鐵塔" },
    { "kanji": "平行線", "kana": "へいこうせん", "romaji": "heikousen", "meaning": "平行線 (酸欠少女さゆり / 動漫熱門曲)" },
    { "kanji": "打上花火", "kana": "うちあげはなび", "romaji": "uchiagehanabi", "meaning": "煙火、升空煙火 (米津玄師/DAOKO)" },
    { "kanji": "パプリカ", "kana": "ぱぷりか", "romaji": "papurika", "meaning": "紅椒 (米津玄師製作全體熱門曲)" },
    { "kanji": "宿命", "kana": "しゅくめい", "romaji": "shukumei", "meaning": "宿命 (Official髭男dism - 宿命)" },
    { "kanji": "怪獣", "kana": "かいじゅう", "romaji": "kaijuu", "meaning": "怪獸 (Vaundy - 怪獣の花唄)" },
    { "kanji": "花唄", "kana": "はなうた", "romaji": "hanauta", "meaning": "哼歌、花歌" },
    { "kanji": "馬と鹿", "kana": "うまとしか", "romaji": "umatoshika", "meaning": "馬與鹿 (米津玄師)" },
    { "kanji": "香水", "kana": "こうすい", "romaji": "kousui", "meaning": "香水 (瑛人 - 香水)" },
    { "kanji": "夜に駆ける", "kana": "よるにかける", "romaji": "yorunikakeru", "meaning": "向夜晚奔去 (YOASOBI 暴紅起點)" },
    { "kanji": "群青", "kana": "ぐんじょう", "romaji": "gunjou", "meaning": "群青 (藍色時期主題合作)" },
    { "kanji": "ハルジオン", "kana": "はるじおん", "romaji": "harujion", "meaning": "春紫菀 (YOASOBI)" },
    { "kanji": "炎", "kana": "ほむら", "romaji": "homura", "meaning": "火焰 (LiSA - 鬼滅之刃無限列車)" },
    { "kanji": "ドライフラワー", "kana": "どらいふらわー", "romaji": "doraifurawaー", "meaning": "乾燥花 (優里 - 霸榜神曲)" },
    { "kanji": "猫", "kana": "ねこ", "romaji": "neko", "meaning": "貓 (DISH// / 北村匠海熱唱)" },
    { "kanji": "感電", "kana": "かんでん", "romaji": "kanden", "meaning": "觸電、感電 (米津玄師)" },
    { "kanji": "春を告げる", "kana": "はるをつげる", "romaji": "haruotsugeru", "meaning": "宣告春天 (yama 網路爆紅)" },
    { "kanji": "閃光", "kana": "せんこう", "romaji": "senkou", "meaning": "閃光 ([Alexandros] - 鋼彈閃光的哈薩威)" },
    { "kanji": "うっせぇわ", "kana": "うっせぇわ", "romaji": "usseewa", "meaning": "煩死了 (Ado 出道即巔峰)" },
    { "kanji": "踊", "kana": "おどり", "romaji": "odori", "meaning": "舞蹈 (Ado 迷幻電子舞曲)" },
    { "kanji": "怪物", "kana": "かいぶつ", "romaji": "kaibutsu", "meaning": "怪物 (YOASOBI - BEASTARS)" },
    { "kanji": "三原色", "kana": "さんげんしょく", "romaji": "sangenrok", "meaning": "三原色" },
    { "kanji": "大正浪漫", "kana": "たいしょうろまん", "romaji": "taishouroman", "meaning": "大正浪漫" },
    { "kanji": "泣き出しそう", "kana": "なきだしそう", "romaji": "nakidashisou", "meaning": "快要哭出來的樣子" },
    { "kanji": "水平線", "kana": "すいへいせん", "romaji": "suiheisen", "meaning": "水平線 (back number 經典)" },
    { "kanji": "高嶺の花子さん", "kana": "たかねのはなこさん", "romaji": "takanenohanakosan", "meaning": "高嶺的花子小姐" },
    { "kanji": "瞬き", "kana": "まばたき", "romaji": "mabataki", "meaning": "閃爍、眨眼" },
    { "kanji": "愛を伝えたいだとか", "kana": "あいをつたえたいだとか", "romaji": "aiotsutaeitaidatoka", "meaning": "傳達愛之類的" },
    { "kanji": "君はロックを聴かない", "kana": "きみはろっくをきかない", "romaji": "kimiharokkuokikanai", "meaning": "你不聽搖滾樂" },
    { "kanji": "裸の心", "kana": "はだかのこころ", "romaji": "hadakanokokoro", "meaning": "赤裸的心" },
    { "kanji": "灰色と青", "kana": "はいいろとあお", "romaji": "haiirotoao", "meaning": "灰色與青 (米津玄師×菅田將暉)" },
    { "kanji": "まちがいさがし", "kana": "まちがいさがし", "romaji": "machigaisagashi", "meaning": "找錯遊戲 (菅田將暉)" },

    // === 1201 - 1300: 2000~2020 ACG 動漫神曲、黃金萬用詞彙篇 ===
    { "kanji": "恍惚", "kana": "こうこつ", "romaji": "koukotsu", "meaning": "恍惚 (平野綾 - God knows...)" },
    { "kanji": "向かい風", "kana": "むかいかぜ", "romaji": "mukaikaze", "meaning": "逆風 (God knows... 經典歌詞)" },
    { "kanji": "夏三角", "kana": "なつさんかく", "romaji": "natsusankaku", "meaning": "夏季大三角 (supercell - 君の知らない物語)" },
    { "kanji": "指差し", "kana": "ゆびさし", "romaji": "yubisashi", "meaning": "用手指著 (指著高空星夜)" },
    { "kanji": "曇天", "kana": "どんてん", "romaji": "donten", "meaning": "陰天 (DOES - 銀魂 OP)" },
    { "kanji": "桃源郷", "kana": "とうげんきょう", "romaji": "tougenkyou", "meaning": "桃源鄉 (銀魂 / ACG熱血意象)" },
    { "kanji": "木ノ葉", "kana": "konoha", "romaji": "konoha", "meaning": "木葉 (火影忍者世界觀 / 青鳥)" },
    { "kanji": "乱舞", "kana": "らんぶ", "romaji": "ranbu", "meaning": "亂舞 (死神 BLEACH 主題曲意象)" },
    { "kanji": "消えない", "kana": "きえない", "romaji": "kienai", "meaning": "無法抹去 (鋼之鍊金術師 - メリッサ)" },
    { "kanji": "絶対遵守", "kana": "ぜったいじゅんしゅ", "romaji": "zettaijunshu", "meaning": "絕對遵守 (Code Geass 反叛的魯路修)" },
    { "kanji": "反逆", "kana": "はんぎゃく", "romaji": "hangyaku", "meaning": "反叛" },
    { "kanji": "世界線", "kana": "せかいせん", "romaji": "sekaisen", "meaning": "世界線 (命運石之門 Steins;Gate)" },
    { "kanji": "観測者", "kana": "かんそくしゃ", "romaji": "kansokusha", "meaning": "觀測者 (時間跳躍/命運石之門)" },
    { "kanji": "百鬼夜行", "kana": "ひゃっきやこう", "romaji": "hyakkiyakou", "meaning": "百鬼夜行 (咒術迴戰0 / King Gnu)" },
    { "kanji": "鳥の詩", "kana": "とりのうた", "romaji": "tori no uta", "meaning": "鳥之詩 (Key 社神作 AIR 主題曲)" },
    { "kanji": "蜩", "kana": "ひぐらし", "romaji": "higashi", "meaning": "暮蟬 (暮蟬悲鳴時意象)" },
    { "kanji": "輪廻", "kana": "りんね", "romaji": "rinne", "meaning": "輪迴" },
    { "kanji": "機動兵器", "kana": "きどうへいき", "romaji": "kidouheiki", "meaning": "機動兵器 (鋼彈 / 機器人番)" },
    { "kanji": "微熱", "kana": "びねつ", "romaji": "binetsu", "meaning": "微熱 (ACG戀愛番高頻詞)" },
    { "kanji": "紅蓮の弓矢", "kana": "ぐれんのゆみや", "romaji": "gurennoyumiya", "meaning": "紅蓮的弓矢 (進擊的巨人 OP1)" },
    { "kanji": "駆逐", "kana": "くちく", "romaji": "kuchiku", "meaning": "驅逐 (進擊的巨人核心詞)" },
    { "kanji": "心臓を捧げよ", "kana": "しんぞうをささげよ", "romaji": "shinzouosasageyo", "meaning": "獻出心臟吧" },
    { "kanji": "コネクト", "kana": "こねくと", "romaji": "konektu", "meaning": "聯繫、Connect (魔法少女小圓 ClariS)" },
    { "kanji": "円環の理", "kana": "えんかんのことわり", "romaji": "enkannonokotowari", "meaning": "圓環之理" },
    { "kanji": "革命", "kana": "かくめい", "romaji": "kakumei", "meaning": "革命 (水樹奈奈×T.M.Revolution)" },
    { "kanji": "創聖", "kana": "そうせい", "romaji": "sousei", "meaning": "創聖 (創聖的大天使)" },
    { "kanji": "一万年", "kana": "いちまんねん", "romaji": "ichimannen", "meaning": "一萬年 (阿姨洗鐵路的核心歌詞)" },
    { "kanji": "愛してる", "kana": "あいしてる", "romaji": "aishiteru", "meaning": "我愛你" },
    { "kanji": "星間飛行", "kana": "せいかんひこう", "romaji": "seikanhikou", "meaning": "星間飛行 (超時空要塞F 綠毛神曲)" },
    { "kanji": "キラッ", "kana": "きらっ", "romaji": "kirat", "meaning": "星光閃耀的一瞬間 (爆頭神曲)" },
    { "kanji": "ライオン", "kana": "らいおん", "romaji": "raion", "meaning": "獅子、Lion (超時空要塞F May'n/中島愛)" },
    { "kanji": "射手座", "kana": "いてざ", "romaji": "iteza", "meaning": "射手座 (不要對我指手畫腳)" },
    { "kanji": "名前のない怪物", "kana": "なまえのないかいぶつ", "romaji": "namaenonaikaibutsu", "meaning": "沒有名字的怪物 (EGOIST - PSYCHO-PASS)" },
    { "kanji": "支配者", "kana": "しはいしゃ", "romaji": "shihaisha", "meaning": "支配者" },
    { "kanji": "此方", "kana": "konata", "romaji": "konata", "meaning": "此處、這個方向 (泉此方 / 幸運星)" },
    { "kanji": "もってけ", "kana": "もってけ", "romaji": "motteke", "meaning": "拿去吧 (幸運星電波 OP)" },
    { "kanji": "唯", "kana": "ゆい", "romaji": "yui", "meaning": "唯、唯一 (K-ON! 輕音少女平澤唯)" },
    { "kanji": "ふわふわタイム", "kana": "ふわふわたいむ", "romaji": "fuwafuwataimu", "meaning": "輕飄飄時間 (放學後茶會 K-ON!)" },
    { "kanji": "美作", "kana": "みさく", "romaji": "misaku", "meaning": "精緻的作品" },
    { "kanji": "シュガーソング", "kana": "しゅがーそんぐ", "romaji": "shugaーsongu", "meaning": "糖果歌 (血界戰線 UNISON SQUARE GARDEN)" },
    { "kanji": "ビターステップ", "kana": "びたーすてっぷ", "romaji": "bitaーsuteppu", "meaning": "苦澀舞步 (血界戰線 ED)" },
    { "kanji": "天界", "kana": "てんかい", "romaji": "tenkai", "meaning": "天界" },
    { "kanji": "地平", "kana": "ちへい", "romaji": "chihei", "meaning": "地平、地平線" },
    { "kanji": "異世界かるてっと", "kana": "いせかいかるてっと", "romaji": "isekaikarutetto", "meaning": "異世界四重奏" },
    { "kanji": "極楽浄土", "kana": "ごくらくじょうど", "romaji": "gokurakujoudo", "meaning": "極樂淨土 (GARNiDELiA 毒品舞曲)" },
    { "kanji": "蝶々", "kana": "ちょうちょう", "romaji": "chouchou", "meaning": "蝴蝶 (極樂淨土歌詞意象)" },
    { "kanji": "艶やか", "kana": "あでやか", "romaji": "adeyaka", "meaning": "艷麗的、嬌豔的" },
    { "kanji": "紅蓮華", "kana": "ぐれんげ", "romaji": "gurenge", "meaning": "紅蓮華 (LiSA - 鬼滅之刃)" },
    { "kanji": "猪突猛進", "kana": "ちょとつもうしん", "romaji": "chototsumoushin", "meaning": "豬突猛進 (嘴平伊之助口頭禪)" },
    { "kanji": "心を燃やせ", "kana": "こころをもやせ", "romaji": "kokoroomoyase", "meaning": "燃燒心靈吧 (煉獄杏壽郎名言)" },
    
    
        // === 笨笨AI整理的===
  { "kanji": "桜", "kana": "さくら", "romaji": "sakura", "meaning": "櫻花" },
  { "kanji": "茜空", "kana": "あかねぞら", "romaji": "akanezora", "meaning": "茜色天空/晚霞" },
  { "kanji": "季節", "kana": "きせつ", "romaji": "kisetsu", "meaning": "季節" },
  { "kanji": "時雨", "kana": "しぐれ", "romaji": "shigure", "meaning": "陣雨/秋末冬初的急雨" },
  { "kanji": "陽炎", "kana": "かげろう", "romaji": "kagerou", "meaning": "陽炎/熱氣晃動" },
  { "kanji": "泡沫", "kana": "うたかた", "romaji": "utakata", "meaning": "泡沫/短暫虛幻物" },
  { "kanji": "閃光", "kana": "せんこう", "romaji": "senkou", "meaning": "閃光" },
  { "kanji": "旅人", "kana": "たびびと", "romaji": "tabibito", "meaning": "旅人/旅客" },
  { "kanji": "故郷", "kana": "こきょう", "romaji": "kokyou", "meaning": "故鄉" },
  { "kanji": "黄昏", "kana": "たそがれ", "romaji": "tasogare", "meaning": "黃昏/傍晚" },
  { "kanji": "暁", "kana": "あかつき", "romaji": "akatsuki", "meaning": "黎明/破曉" },
  { "kanji": "夜明け", "kana": "よあけ", "romaji": "yoake", "meaning": "黎明/天亮" },
  { "kanji": "新月", "kana": "しんげつ", "romaji": "shingetsu", "meaning": "新月" },
  { "kanji": "満月", "kana": "まんげつ", "romaji": "mangetsu", "meaning": "滿月" },
  { "kanji": "流星", "kana": "りゅうせい", "romaji": "ryuusei", "meaning": "流星" },
  { "kanji": "銀河", "kana": "ぎんが", "romaji": "ginga", "meaning": "銀河" },
  { "kanji": "彗星", "kana": "すいせい", "romaji": "suisei", "meaning": "彗星" },
  { "kanji": "星座", "kana": "せいざ", "romaji": "seiza", "meaning": "星座" },
  { "kanji": "宇宙", "kana": "うちゅう", "romaji": "uchuu", "meaning": "宇宙" },
  { "kanji": "青空", "kana": "あおぞら", "romaji": "aozora", "meaning": "藍天" },
  { "kanji": "夕日", "kana": "ゆうひ", "romaji": "yuuhi", "meaning": "夕陽" },
  { "kanji": "木漏れ日", "kana": "こもれび", "romaji": "komorebi", "meaning": "從樹葉縫隙漏落的陽光" },
  { "kanji": "足跡", "kana": "あしあと", "romaji": "ashiato", "meaning": "腳印/足跡" },
  { "kanji": "軌跡", "kana": "きせき", "romaji": "kiseki", "meaning": "軌跡" },
  { "kanji": "歴史", "kana": "れきし", "romaji": "rekishi", "meaning": "歷史" },
  { "kanji": "物語", "kana": "ものがたり", "romaji": "monogatari", "meaning": "故事/傳說" },
  { "kanji": "約束", "kana": "やくそく", "romaji": "yakusoku", "meaning": "約定/承諾" },
  { "kanji": "鍵", "kana": "かぎ", "romaji": "kagi", "meaning": "鑰匙" },
  { "kanji": "時計", "kana": "とけい", "romaji": "tokei", "meaning": "時鐘/手錶" },
  { "kanji": "歯車", "kana": "はぐるま", "romaji": "haguruma", "meaning": "齒輪" },
  { "kanji": "劇場", "kana": "げきじょう", "romaji": "gekijou", "meaning": "劇場" },
  { "kanji": "舞台", "kana": "ぶたい", "romaji": "butai", "meaning": "舞台" },
  { "kanji": "衣装", "kana": "いしょう", "romaji": "ishou", "meaning": "服裝/衣裳" },
  { "kanji": "仮面", "kana": "かめん", "romaji": "kamen", "meaning": "面具/假面" },
  { "kanji": "人形", "kana": "にんぎょう", "romaji": "ningyou", "meaning": "玩偶/娃娃" },
  { "kanji": "魔法", "kana": "まほう", "romaji": "mahou", "meaning": "魔法" },
  { "kanji": "魔王", "kana": "まおう", "romaji": "maou", "meaning": "魔王" },
  { "kanji": "騎士", "kana": "きし", "romaji": "kishi", "meaning": "騎士" },
  { "kanji": "武器", "kana": "ぶき", "romaji": "buki", "meaning": "武器" },
  { "kanji": "防具", "kana": "ぼうぐ", "romaji": "bougu", "meaning": "防具" },
  { "kanji": "勝利", "kana": "しょうり", "romaji": "shouri", "meaning": "勝利" },
  { "kanji": "敗北", "kana": "はいぼく", "romaji": "haiboku", "meaning": "敗北/失敗" },
  { "kanji": "戦い", "kana": "たたかい", "romaji": "tatakai", "meaning": "戰鬥/戰爭" },
  { "kanji": "平和", "kana": "へいわ", "romaji": "heiwa", "meaning": "和平" },
  { "kanji": "自由", "kana": "じゆう", "romaji": "jiyuu", "meaning": "自由" },
  { "kanji": "正義", "kana": "せいぎ", "romaji": "seigi", "meaning": "正義" },
  { "kanji": "覚悟", "kana": "かくご", "romaji": "kakugo", "meaning": "做好心理準備/覺悟" },
  { "kanji": "衝動", "kana": "しょうどう", "romaji": "shoudou", "meaning": "衝動" },
  { "kanji": "本能", "kana": "ほんのう", "romaji": "honnou", "meaning": "本能" },
  { "kanji": "理性", "kana": "りせい", "romaji": "risei", "meaning": "理性" },
  { "kanji": "感情", "kana": "かんじょう", "romaji": "kanjou", "meaning": "感情/情緒" },
  { "kanji": "愛情", "kana": "あいじょう", "romaji": "aijou", "meaning": "愛情" },
  { "kanji": "友情", "kana": "ゆうじょう", "romaji": "yuujou", "meaning": "友情" },
  { "kanji": "初恋", "kana": "はつこい", "romaji": "hatsukoi", "meaning": "初戀" },
  { "kanji": "失恋", "kana": "しつれん", "romaji": "shitsuren", "meaning": "失戀" },
  { "kanji": "刹那", "kana": "せつな", "romaji": "setsuna", "meaning": "剎那" },
  { "kanji": "現在", "kana": "げんざい", "romaji": "genzai", "meaning": "現在" },
  { "kanji": "過去", "kana": "かこ", "romaji": "kako", "meaning": "過去" },
  { "kanji": "来世", "kana": "らいせ", "romaji": "raise", "meaning": "來世/下輩子" },
  { "kanji": "現世", "kana": "げんせ", "romaji": "gense", "meaning": "現世/這輩子" },
  
  // ===  彩蛋
  { "kanji": "楽団", "kana": "がくだん", "romaji": "gakudan", "meaning": "樂團/樂隊" },
  { "kanji": "伴走", "kana": "ばんそう", "romaji": "bansou", "meaning": "伴奏/伴跑" },
  { "kanji": "燈火", "kana": "ともしび", "romaji": "tomoshibi", "meaning": "燈火/微光" },
  { "kanji": "迷星", "kana": "めいせい", "romaji": "meisei", "meaning": "迷失之星" },
  { "kanji": "碧天", "kana": "へきたん", "romaji": "hekitan", "meaning": "碧空/藍天" },
  { "kanji": "一生", "kana": "いっしょう", "romaji": "isshou", "meaning": "一生/一輩子" },
  { "kanji": "歌詞", "kana": "かし", "romaji": "kashi", "meaning": "歌詞" },
  { "kanji": "楽譜", "kana": "がくふ", "romaji": "gakufu", "meaning": "樂譜" },
  { "kanji": "音色", "kana": "ねいろ", "romaji": "neiro", "meaning": "音色" },
  { "kanji": "残響", "kana": "ざんきょう", "romaji": "zankyou", "meaning": "殘響/餘音" },
  { "kanji": "叫び", "kana": "さけび", "romaji": "sakebi", "meaning": "吶喊/呼喊" },
  { "kanji": "咆哮", "kana": "ほうこう", "romaji": "houkou", "meaning": "咆哮/嘶吼" },
  { "kanji": "居場所", "kana": "いばしょ", "romaji": "ibasho", "meaning": "容身之處/歸屬" },
  { "kanji": "人形劇", "kana": "にんぎょうげき", "romaji": "ningyougeki", "meaning": "人偶劇/木偶戲" },
  { "kanji": "操り人形", "kana": "あやつりにんぎょう", "romaji": "ayatsuri ningyou", "meaning": "傀儡/牽線木偶" },
  { "kanji": "漆黒", "kana": "しっこく", "romaji": "shikkoku", "meaning": "漆黑" },
  { "kanji": "頂点", "kana": "ちょうてん", "romaji": "chouten", "meaning": "頂點" },
  { "kanji": "狂気", "kana": "きょうき", "romaji": "kyouki", "meaning": "狂氣/瘋狂" },
  { "kanji": "崩壊", "kana": "ほうかい", "romaji": "houkai", "meaning": "崩壞" },
  { "kanji": "再生", "kana": "さいせい", "romaji": "saisei", "meaning": "再生/復活" },
  { "kanji": "覚醒", "kana": "かくせい", "romaji": "kaksei", "meaning": "覺醒" },
  { "kanji": "旋律", "kana": "せんりつ", "romaji": "senritsu", "meaning": "旋律" },
  { "kanji": "和音", "kana": "わおん", "romaji": "waon", "meaning": "和音/和弦" },
  { "kanji": "共鳴", "kana": "きょうめい", "romaji": "kyoumei", "meaning": "共鳴" },
  { "kanji": "激情", "kana": "げきじょう", "romaji": "gekijou", "meaning": "激情" },
  { "kanji": "渇望", "kana": "かつぼう", "romaji": "katsubou", "meaning": "渴望" },
  { "kanji": "絶望", "kana": "ぜつぼう", "romaji": "zetsubou", "meaning": "絕望" },
  { "kanji": "歓喜", "kana": "かんき", "romaji": "kanki", "meaning": "歡喜/狂喜" },
  { "kanji": "星空", "kana": "ほしぞら", "romaji": "hoshizora", "meaning": "星空" },
  { "kanji": "夜空", "kana": "よぞら", "romaji": "yozora", "meaning": "夜空" },
  { "kanji": "満天", "kana": "まんてん", "romaji": "manten", "meaning": "滿天" },
  { "kanji": "閃き", "kana": "ひらめき", "romaji": "hirameki", "meaning": "靈感/閃現" },
  { "kanji": "心音", "kana": "しんおん", "romaji": "shinon", "meaning": "心跳聲" },
  { "kanji": "息吹", "kana": "いぶき", "romaji": "ibuki", "meaning": "氣息/生機" },
  { "kanji": "素顔", "kana": "すがお", "romaji": "sugao", "meaning": "素顏/真實面貌" },
  { "kanji": "本音", "kana": "ほんね", "romaji": "honne", "meaning": "真心話/真心" },
  { "kanji": "建前", "kana": "たてまえ", "romaji": "tatemae", "meaning": "表面話/客套話" },
  { "kanji": "裏切り", "kana": "うらぎり", "romaji": "uragiri", "meaning": "背叛" },
  { "kanji": "執着", "kana": "しゅうちゃく", "romaji": "shuuchaku", "meaning": "執著" },
  { "kanji": "依存", "kana": "いぞん", "romaji": "izon", "meaning": "依賴/依存" },
  { "kanji": "解散", "kana": "かいさん", "romaji": "kaisan", "meaning": "解散" },
  { "kanji": "結成", "kana": "けっせい", "romaji": "kessei", "meaning": "結成/成立" },
  { "kanji": "青春", "kana": "せいしゅん", "romaji": "seishun", "meaning": "青春" },
  { "kanji": "迷路", "kana": "めいろ", "romaji": "meiro", "meaning": "迷宮" },
  { "kanji": "泥濘", "kana": "ぬかるみ", "romaji": "nukarumi", "meaning": "泥濘" },
  { "kanji": "雨上がり", "kana": "あめあがり", "romaji": "ameagari", "meaning": "雨後天晴" },
  { "kanji": "砂時計", "kana": "すなどけい", "romaji": "sunadokei", "meaning": "沙漏" },
  { "kanji": "嘘つき", "kana": "うそつき", "romaji": "usotsuki", "meaning": "騙子" },
  { "kanji": "救い", "kana": "すくい", "romaji": "sukui", "meaning": "救贖/拯救" },
  { "kanji": "罪", "kana": "つみ", "romaji": "tsumi", "meaning": "罪過/罪惡" },
  { "kanji": "罰", "kana": "ばつ", "romaji": "batsu", "meaning": "懲罰" },
  { "kanji": "聖域", "kana": "せいいき", "romaji": "seiiki", "meaning": "聖域" },
  { "kanji": "楽園", "kana": "らくえん", "romaji": "rakuen", "meaning": "樂園" },
  { "kanji": "巡り合わせ", "kana": "めぐりあわせ", "romaji": "meguriawase", "meaning": "因緣/宿命的相遇" },
  { "kanji": "指先", "kana": "ゆびさき", "romaji": "yubisaki", "meaning": "指尖" },
  { "kanji": "爪痕", "kana": "つめあと", "romaji": "tsumeato", "meaning": "抓痕/留下的痕跡" },
  { "kanji": "終焉", "kana": "しゅうえん", "romaji": "shuuen", "meaning": "終焉/結局" },
  { "kanji": "舞台裏", "kana": "ぶたいうら", "romaji": "butaiura", "meaning": "舞台幕後/後台" },
  { "kanji": "拍手", "kana": "はくしゅ", "romaji": "hakushu", "meaning": "掌聲/拍手" },
  { "kanji": "喝采", "kana": "かっさい", "romaji": "kassai", "meaning": "喝采/喝彩" },
  
  { "kanji": "陽だまり", "kana": "ひだまり", "romaji": "hidamari", "meaning": "陽光照耀的溫暖之處/向陽處" },
  { "kanji": "面影", "kana": "おもかげ", "romaji": "omokage", "meaning": "面容/身影/留下的影子" },
  { "kanji": "ぬくもり", "kana": "ぬくもり", "romaji": "nukumori", "meaning": "溫慢/餘溫" },
  { "kanji": "逃げ場所", "kana": "にげばしょ", "romaji": "nigebasho", "meaning": "逃跑之處/避難所" },
  { "kanji": "星屑", "kana": "ほしくず", "romaji": "hoshikuzu", "meaning": "星屑/碎星" },
  { "kanji": "叫び声", "kana": "さけびごえ", "romaji": "sakebigoe", "meaning": "吶喊聲/呼喊聲" },
  { "kanji": "現実", "kana": "げんじつ", "romaji": "genjitsu", "meaning": "現實" },
  { "kanji": "幻想", "kana": "げんそう", "romaji": "gensou", "meaning": "幻想" },
  { "kanji": "屋上", "kana": "おくじょう", "romaji": "okujou", "meaning": "頂樓/屋頂" },
  { "kanji": "碧空", "kana": "へきくう", "romaji": "hekikuu", "meaning": "碧空/藍天" },
  { "kanji": "土砂降り", "kana": "どしゃぶり", "romaji": "doshaburi", "meaning": "傾盆大雨" },
  { "kanji": "泥だらけ", "kana": "どろだらけ", "romaji": "dorodarake", "meaning": "滿是泥濘/沾滿泥土" },
  { "kanji": "協奏", "kana": "きょうそう", "romaji": "kyousou", "meaning": "協奏" },
  { "kanji": "手のひら", "kana": "てのひら", "romaji": "tenohira", "meaning": "手掌/手心" },
  { "kanji": "糸", "kana": "いと", "romaji": "ito", "meaning": "線/絲線" },
  { "kanji": "紡ぐ", "kana": "つむぐ", "romaji": "tsumugu", "meaning": "紡織/編織/細訴" },
  { "kanji": "運命線", "kana": "うんめいせん", "romaji": "unmeisen", "meaning": "命運線" },
  { "kanji": "栞", "kana": "しおり", "romaji": "shiori", "meaning": "書籤" },
  { "kanji": "ページ", "kana": "ぺーじ", "romaji": "peeji", "meaning": "頁面/篇章" },
  { "kanji": "行間", "kana": "ぎょうかん", "romaji": "gyoukan", "meaning": "字裡行間" },
  { "kanji": "詩", "kana": "うた", "romaji": "uta", "meaning": "詩/歌詞" },
  { "kanji": "剥き出し", "kana": "むきだし", "romaji": "mukidashi", "meaning": "赤裸/暴露/毫無保留" },
  { "kanji": "不器用", "kana": "ぶきよう", "romaji": "bukiyou", "meaning": "笨拙/不靈巧" },
  { "kanji": "独りぼっち", "kana": "ひとりぼっち", "romaji": "hitoribocchi", "meaning": "孤單一人/無依無靠" },
  { "kanji": "震える", "kana": "ふるえる", "romaji": "furueru", "meaning": "顫抖/發抖" },
  { "kanji": "心臓", "kana": "しんぞう", "romaji": "shinzou", "meaning": "心臟" },
  { "kanji": "鼓膜", "kana": "こまく", "romaji": "komaku", "meaning": "耳膜/鼓膜" },
  { "kanji": "灰色", "kana": "はいいろ", "romaji": "haiiro", "meaning": "灰色" },
  { "kanji": "過呼吸", "kana": "かこきゅう", "romaji": "kakokyuu", "meaning": "換氣過度/過呼吸" },
  { "kanji": "感情論", "kana": "かんじょうろん", "romaji": "kanjouron", "meaning": "感情論/意氣之爭" },
  { "kanji": "綺麗事", "kana": "きれいごと", "romaji": "kireigoto", "meaning": "漂亮話/場面話" },
  { "kanji": "遮断", "kana": "しゃだん", "romaji": "shadan", "meaning": "遮斷/隔絕" },
  { "kanji": "輪郭", "kana": "りんかく", "romaji": "rinkaku", "meaning": "輪廓" },
  { "kanji": "ステップ", "kana": "すてっぷ", "romaji": "suteppu", "meaning": "舞步/步伐" },
  { "kanji": "残像", "kana": "ざんぞう", "romaji": "zanzou", "meaning": "殘像/餘影" },
  { "kanji": "境界", "kana": "きょうかい", "romaji": "kyoukai", "meaning": "境界/邊界" },
  { "kanji": "仮面劇", "kana": "かめんげき", "romaji": "kamengeki", "meaning": "假面劇" },
  { "kanji": "暗闇", "kana": "くらやみ", "romaji": "kurayami", "meaning": "黑暗/暗處" },
  { "kanji": "秘め事", "kana": "ひめごと", "romaji": "himegoto", "meaning": "隱密的事/秘密" },
  { "kanji": "迷宮", "kana": "めいきゅう", "romaji": "meikyuu", "meaning": "迷宮" },
  { "kanji": "贖罪", "kana": "しょくざい", "romaji": "shokuzai", "meaning": "贖罪" },
  { "kanji": "混沌", "kana": "こんとん", "romaji": "konton", "meaning": "混沌" },
  { "kanji": "虚像", "kana": "きょぞう", "romaji": "kyozou", "meaning": "虛像/幻象" },
  { "kanji": "支配", "kana": "しはい", "romaji": "shihai", "meaning": "支配/控制" },
  { "kanji": "盲目", "kana": "もうもく", "romaji": "moumoku", "meaning": "盲目" },
  { "kanji": "悲劇", "kana": "ひげき", "romaji": "higeki", "meaning": "悲劇" },
  { "kanji": "喜劇", "kana": "きげき", "romaji": "kigeki", "meaning": "喜劇" },
  { "kanji": "狂い咲き", "kana": "くるいざき", "romaji": "kuruizaki", "meaning": "錯季開花/瘋狂綻放" },
  { "kanji": "頂", "kana": "いただき", "romaji": "itadaki", "meaning": "頂點/巔峰" },
  { "kanji": "蒼炎", "kana": "そうえん", "romaji": "souen", "meaning": "蒼藍火焰" },
  { "kanji": "執念", "kana": "しゅうねん", "romaji": "shuunen", "meaning": "執念" },
  { "kanji": "誇り", "kana": "ほこり", "romaji": "hokori", "meaning": "驕傲/自豪" },
  { "kanji": "薔薇", "kana": "ばら", "romaji": "bara", "meaning": "薔薇/玫瑰" },
  { "kanji": "茨", "kana": "いばら", "romaji": "ibara", "meaning": "荊棘" },
  { "kanji": "誓い", "kana": "ちかい", "romaji": "chikai", "meaning": "誓言/誓約" },
  { "kanji": "絶叫", "kana": "ぜっきょう", "romaji": "zekkyou", "meaning": "絕叫/慘叫/大喊" },
  { "kanji": "歌姫", "kana": "うたひめ", "romaji": "utahime", "meaning": "歌姬" },
  { "kanji": "繋がり", "kana": "つながり", "romaji": "tsunagari", "meaning": "聯繫/連結/牽絆" },
  { "kanji": "烈火", "kana": "れっか", "romaji": "rekka", "meaning": "烈火" },
  { "kanji": "悠久", "kana": "ゆうきゅう", "romaji": "yuukyuu", "meaning": "悠久/永恆" },
  
  
  //=== Re 0:

  { "kanji": "異世界", "kana": "いせかい", "romaji": "isekai", "meaning": "異世界" },
  { "kanji": "死に戻り", "kana": "しにもどり", "romaji": "shinimodori", "meaning": "死亡回歸" },
  { "kanji": "魔女", "kana": "まじょ", "romaji": "majo", "meaning": "魔女" },
  { "kanji": "大罪", "kana": "たいざい", "romaji": "taizai", "meaning": "大罪" },
  { "kanji": "司教", "kana": "しきょう", "romaji": "shikyou", "meaning": "司教/主教" },
  { "kanji": "福音書", "kana": "ふくいんしょ", "romaji": "fukuinsho", "meaning": "福音書" },
  { "kanji": "精霊", "kana": "せいれい", "romaji": "seirei", "meaning": "精靈" },
  { "kanji": "契約", "kana": "けいやく", "romaji": "keiyaku", "meaning": "契約" },
  { "kanji": "加護", "kana": "かご", "romaji": "kago", "meaning": "加護/神聖庇護" },
  { "kanji": "魔獣", "kana": "まじゅう", "romaji": "majuu", "meaning": "魔獸" },
  { "kanji": "残り香", "kana": "のこりが", "romaji": "nokoriga", "meaning": "殘留的氣味/餘香" },
  { "kanji": "寵愛", "kana": "ちょうあい", "romaji": "chouai", "meaning": "寵愛" },
  { "kanji": "怠惰", "kana": "たいだ", "romaji": "taida", "meaning": "怠惰" },
  { "kanji": "強欲", "kana": "ごうよく", "romaji": "gouyoku", "meaning": "強欲/貪婪" },
  { "kanji": "嫉妬", "kana": "しっと", "romaji": "shitto", "meaning": "嫉妒" },
  { "kanji": "傲慢", "kana": "ごうまん", "romaji": "gouman", "meaning": "傲慢" },
  { "kanji": "憤怒", "kana": "ふんど", "romaji": "fundo", "meaning": "憤怒" },
  { "kanji": "暴食", "kana": "ぼうしょく", "romaji": "boushoku", "meaning": "暴食" },
  { "kanji": "色欲", "kana": "しきよく", "romaji": "shikiyoku", "meaning": "色欲" },
  { "kanji": "試練", "kana": "しれん", "romaji": "shiren", "meaning": "試煉/考驗" },
  { "kanji": "禁書庫", "kana": "きんしょこ", "romaji": "kinshoko", "meaning": "禁書庫" },
  { "kanji": "鬼化", "kana": "おにか", "romaji": "onika", "meaning": "鬼化/惡魔化" },
  { "kanji": "千里眼", "kana": "せんりがん", "romaji": "senrigan", "meaning": "千里眼" },
  { "kanji": "白鯨", "kana": "はくげい", "romaji": "hakugei", "meaning": "白鯨" },
  { "kanji": "大兎", "kana": "おおうさぎ", "romaji": "oousagi", "meaning": "大兔" },
  { "kanji": "黒蛇", "kana": "くろへび", "romaji": "kurohebi", "meaning": "黑蛇" },
  { "kanji": "ループ", "kana": "るーぷ", "romaji": "ruupu", "meaning": "循環/死循環" },
  { "kanji": "抗う", "kana": "あらがう", "romaji": "aragau", "meaning": "反抗/抗爭/對抗" },
  { "kanji": "救い出す", "kana": "すくいだす", "romaji": "sukuidasu", "meaning": "救出/拯救出來" },
  { "kanji": "悲痛", "kana": "ひつう", "romaji": "hitsuu", "meaning": "悲痛/極度痛苦" },
  { "kanji": "英雄", "kana": "えいゆう", "romaji": "eiyuu", "meaning": "英雄" },
  { "kanji": "一途", "kana": "いちず", "romaji": "ichizu", "meaning": "專一/一心一意" },
  { "kanji": "未練", "kana": "みれん", "romaji": "miren", "meaning": "依戀/迷戀/留戀" },
  { "kanji": "忘却", "kana": "ぼうきゃく", "romaji": "boukyaku", "meaning": "忘卻/遺忘" },
  { "kanji": "因果", "kana": "いんが", "romaji": "inga", "meaning": "因果" },
  { "kanji": "奈落", "kana": "ならく", "romaji": "naraku", "meaning": "奈落/地獄/深淵" },
  { "kanji": "決意", "kana": "けつい", "romaji": "ketsui", "meaning": "決意/決心" },
  { "kanji": "悲鳴", "kana": "ひめい", "romaji": "himei", "meaning": "悲鳴/慘叫" },
  { "kanji": "慈愛", "kana": "じあい", "romaji": "jiai", "meaning": "慈愛" },
  { "kanji": "愛おしい", "kana": "いとおしい", "romaji": "itooshii", "meaning": "可愛的/令人憐愛的" },
  { "kanji": "狂信", "kana": "きょうしん", "romaji": "kyoushin", "meaning": "狂信/盲目信仰" },
  { "kanji": "断罪", "kana": "だんざい", "romaji": "danzai", "meaning": "斷罪/判定罪刑" },
  { "kanji": "祝福", "kana": "しゅくふく", "romaji": "shukufuku", "meaning": "祝福" },
  { "kanji": "結晶", "kana": "けっしょう", "romaji": "kesshou", "meaning": "結晶" },
  { "kanji": "近衛", "kana": "このえ", "romaji": "konoe", "meaning": "近衛/皇家衛隊" },
  { "kanji": "螺旋", "kana": "らせん", "romaji": "rasen", "meaning": "螺旋" },
  { "kanji": "彷徨う", "kana": "さまよう", "romaji": "samayou", "meaning": "徘徊/彷徨" },
  { "kanji": "惨劇", "kana": "さんげき", "romaji": "sangeki", "meaning": "慘劇" },
  { "kanji": "怨念", "kana": "おんねん", "romaji": "onnen", "meaning": "怨念" },
  { "kanji": "決死", "kana": "けっし", "romaji": "kesshi", "meaning": "決死/抱著必死決心" },
  { "kanji": "命懸け", "kana": "いのちがけ", "romaji": "inochigake", "meaning": "拼命/冒著生命危險" },
  { "kanji": "身代わり", "kana": "みがわり", "romaji": "migawari", "meaning": "替身/代罪羔羊" },
  { "kanji": "白昼夢", "kana": "はくちゅうむ", "romaji": "hakuchuumu", "meaning": "白日夢" },
  { "kanji": "眩暈", "kana": "めまい", "romaji": "memai", "meaning": "暈眩/眼花" },
  { "kanji": "吐息", "kana": "といき", "romaji": "toiki", "meaning": "吐息/嘆氣" },
  { "kanji": "リセット", "kana": "りせっと", "romaji": "risetto", "meaning": "重置/Reset" },
  { "kanji": "リスタート", "kana": "りすたーと", "romaji": "risutaato", "meaning": "重新開始/Restart" },
  { "kanji": "迷い路", "kana": "まよいじ", "romaji": "mayoiji", "meaning": "迷途/迷惘的道路" },
  { "kanji": "終末", "kana": "しゅうまつ", "romaji": "shuumatsu", "meaning": "終末/世界末日" },
  { "kanji": "ゼロ", "kana": "ぜろ", "romaji": "zero", "meaning": "零/從零開始" }
  
];