
// vocab.js
// 2026 最新日K & 動漫J-POP高頻核心字庫 (精選200組落地)
const OFFLINE_VOCAB_DB = [
    // === 001 - 025: 命運、世界與希望篇 (動漫開場神曲高頻詞) ===
    { "kanji": "残酷", "kana": "ざんこく", "romaji": "zankoku", "meaning": "殘酷的 (殘酷天使的行動綱領)" },
    { "kanji": "天使", "kana": "てんし", "romaji": "tenshi", "meaning": "天使" },
    { "kanji": "神話", "kana": "しんわ", "romaji": "shinwa", "meaning": "神話" },
    { "kanji": "運命", "kana": "うんめい", "romaji": "unmei", "meaning": "命運" },
    { "kanji": "世界", "kana": "せかい", "romaji": "sekai", "meaning": "世界" },
    { "kanji": "秘密", "kana": "ひみつ", "romaji": "himitsu", "meaning": "秘密 (Idol 歌詞)" },
    { "kanji": "完璧", "kana": "かんぺき", "romaji": "kanpeki", "meaning": "完美的" },
    { "kanji": "未来", "kana": "みらい", "romaji": "mirai", "meaning": "未來" },
    { "kanji": "心", "kana": "こころ", "romaji": "kokoro", "meaning": "心、心靈" },
    { "kanji": "明日", "kana": "あした", "romaji": "ashita", "meaning": "明天" },
    { "kanji": "絆", "kana": "きずな", "romaji": "kizuna", "meaning": "羈絆" },
    { "kanji": "奇跡", "kana": "きせき", "romaji": "kiseki", "meaning": "奇蹟" },
    { "kanji": "情熱", "kana": "じょうねつ", "romaji": "jounetsu", "meaning": "熱情" },
    { "kanji": "孤独", "kana": "こどく", "romaji": "kodoku", "meaning": "孤獨" },
    { "kanji": "記憶", "kana": "きおく", "romaji": "kioku", "meaning": "記憶" },
    { "kanji": "真実", "kana": "しんじつ", "romaji": "shinjitsu", "meaning": "真實" },
    { "kanji": "永遠", "kana": "えいえん", "romaji": "eien", "meaning": "永遠" },
    { "kanji": "自由", "kana": "じゆう", "romaji": "jiyuu", "meaning": "自由 (進擊的巨人)" },
    { "kanji": "希望", "kana": "きぼう", "romaji": "kibou", "meaning": "希望" },
    { "kanji": "光", "kana": "ひかり", "romaji": "hikari", "meaning": "光芒" },
    { "kanji": "魂", "kana": "たましい", "romaji": "tamashii", "meaning": "靈魂" },
    { "kanji": "一步", "kana": "いっぽ", "romaji": "ippo", "meaning": "一步" },
    { "kanji": "限界", "kana": "げんかい", "romaji": "genkai", "meaning": "極限" },
    { "kanji": "幻想", "kana": "げんそう", "romaji": "gensou", "meaning": "幻想" },
    { "kanji": "覚醒", "kana": "かくせい", "romaji": "kaksei", "meaning": "覺醒" },

    // === 026 - 050: 戰鬥、鮮血與熱血篇 (鬼滅、咒術、火影系列) ===
    { "kanji": "紅蓮", "kana": "ぐれん", "romaji": "guren", "meaning": "紅蓮 (紅蓮華)" },
    { "kanji": "運命", "kana": "さだめ", "romaji": "sadame", "meaning": "宿命 (常唱作さだめ)" },
    { "kanji": "情熱", "kana": "じょうねつ", "romaji": "jounetsu", "meaning": "熱情" },
    { "kanji": "泥", "kana": "どろ", "romaji": "doro", "meaning": "泥巴" },
    { "kanji": "刃", "kana": "やいば", "romaji": "yaiba", "meaning": "刀刃" },
    { "kanji": "強さ", "kana": "つよさ", "romaji": "tsuyosa", "meaning": "堅強、力量" },
    { "kanji": "呪い", "kana": "のろい", "romaji": "noroi", "meaning": "詛咒" },
    { "kanji": "廻廻", "kana": "かいかい", "romaji": "kaikai", "meaning": "迴迴" },
    { "kanji": "青空", "kana": "あおぞら", "romaji": "aozora", "meaning": "藍天" },
    { "kanji": "蒼い", "kana": "あおい", "romaji": "aoi", "meaning": "藍色的 (青鳥)" },
    { "kanji": "悲しみ", "kana": "かなしみ", "romaji": "kanashimi", "meaning": "悲傷" },
    { "kanji": "羽ばたく", "kana": "はばたく", "romaji": "habataku", "meaning": "展翅高飛" },
    { "kanji": "鼓動", "kana": "こどう", "romaji": "kodou", "meaning": "心跳、鼓動" },
    { "kanji": "宿命", "kana": "しゅくめい", "romaji": "shukumei", "meaning": "宿命" },
    { "kanji": "衝動", "kana": "しょうどう", "romaji": "shoudou", "meaning": "衝動" },
    { "kanji": "正義", "kana": "せいぎ", "romaji": "seigi", "meaning": "正義" },
    { "kanji": "覚悟", "kana": "かくご", "romaji": "kakugo", "meaning": "覺悟" },
    { "kanji": "絶望", "kana": "ぜつぼう", "romaji": "zetsubou", "meaning": "絕望" },
    { "kanji": "勝利", "kana": "しょうり", "romaji": "shouri", "meaning": "勝利" },
    { "kanji": "敗北", "kana": "はいぼく", "romaji": "haiboku", "meaning": "敗北" },
    { "kanji": "暗闇", "kana": "くらやみ", "romaji": "kurayami", "meaning": "黑暗" },
    { "kanji": "稲妻", "kana": "いなずま", "romaji": "inazuma", "meaning": "閃電" },
    { "kanji": "烈火", "kana": "れっか", "romaji": "rekka", "meaning": "烈火" },
    { "kanji": "闘志", "kana": "とうし", "romaji": "toushi", "meaning": "鬥志" },
    { "kanji": "修羅", "kana": "しゅら", "romaji": "shura", "meaning": "修羅" },

    // === 051 - 075: 星空、夜晚與都市感篇 (YOASOBI、Vaundy、美音) ===
    { "kanji": "夜", "kana": "よる", "romaji": "yoru", "meaning": "夜晚 (向夜晚奔去)" },
    { "kanji": "駆ける", "kana": "かける", "romaji": "kakeru", "meaning": "奔跑" },
    { "kanji": "沈む", "kana": "しずむ", "romaji": "shizumu", "meaning": "下沉" },
    { "kanji": "怪獣", "kana": "かいじゅう", "romaji": "kaijuu", "meaning": "怪獸 (怪獸的花歌)" },
    { "kanji": "花唄", "kana": "はなうた", "romaji": "hanauta", "meaning": "哼歌、花歌" },
    { "kanji": "踊り", "kana": "おどり", "romaji": "odori", "meaning": "舞蹈 (Ado - 踊)" },
    { "kanji": "新時代", "kana": "しんじだい", "romaji": "shinjidai", "meaning": "新時代 (ONE PIECE FILM RED)" },
    { "kanji": "東京", "kana": "とうきょう", "romaji": "toukyou", "meaning": "東京" },
    { "kanji": "逆光", "kana": "ぎゃっこう", "romaji": "gyakkou", "meaning": "逆光" },
    { "kanji": "残響", "kana": "ざんきょう", "romaji": "zankyou", "meaning": "殘響 (殘響散歌)" },
    { "kanji": "散歌", "kana": "さんか", "romaji": "sanka", "meaning": "散歌" },
    { "kanji": "朝霧", "kana": "あさぎり", "romaji": "asagiri", "meaning": "晨霧" },
    { "kanji": "真夜中", "kana": "まよなか", "romaji": "mayonaka", "meaning": "午夜、連夜" },
    { "kanji": "星座", "kana": "せいざ", "romaji": "seiza", "meaning": "星座" },
    { "kanji": "流星", "kana": "りゅうせい", "romaji": "ryuusei", "meaning": "流星" },
    { "kanji": "銀河", "kana": "ぎんが", "romaji": "ginga", "meaning": "銀河" },
    { "kanji": "彗星", "kana": "すいせい", "romaji": "suisei", "meaning": "彗星" },
    { "kanji": "月光", "kana": "げっこう", "romaji": "gekkou", "meaning": "月光" },
    { "kanji": "夜明け", "kana": "よあけ", "romaji": "yoake", "meaning": "黎明、拂曉" },
    { "kanji": "都会", "kana": "とかい", "romaji": "tokai", "meaning": "都市" },
    { "kanji": "喧騒", "kana": "けんそう", "romaji": "kensou", "meaning": "喧囂" },
    { "kanji": "静寂", "kana": "せいじゃく", "romaji": "seijaku", "meaning": "寂靜" },
    { "kanji": "ネオン", "kana": "ねおん", "romaji": "neon", "meaning": "霓虹燈" },
    { "kanji": "ステップ", "kana": "すてっぷ", "romaji": "suteppu", "meaning": "舞步 (Step)" },
    { "kanji": "メロディ", "kana": "めろでぃ", "romaji": "merodi", "meaning": "旋律" },

    // === 076 - 100: 情感、淚水與思念篇 (青春、抒情歌、日K必點) ===
    { "kanji": "愛", "kana": "あい", "romaji": "ai", "meaning": "愛" },
    { "kanji": "恋", "kana": "こい", "romaji": "koi", "meaning": "戀愛 (星野源 - 戀)" },
    { "kanji": "涙", "kana": "なみだ", "romaji": "namida", "meaning": "淚水" },
    { "kanji": "笑顔", "kana": "えがお", "romaji": "egao", "meaning": "笑容" },
    { "kanji": "瞳", "kana": "ひとみ", "romaji": "hitomi", "meaning": "眼睛、瞳孔" },
    { "kanji": "嘘", "kana": "うそ", "romaji": "uso", "meaning": "謊言" },
    { "kanji": "初恋", "kana": "ハツコイ", "romaji": "hatsukoi", "meaning": "初戀" },
    { "kanji": "言葉", "kana": "ことば", "romaji": "kotoba", "meaning": "言語、字句" },
    { "kanji": "約束", "kana": "やくそく", "romaji": "yaksoku", "meaning": "約定" },
    { "kanji": "さよなら", "kana": "さよなら", "romaji": "sayonara", "meaning": "再見" },
    { "kanji": "ありがとう", "kana": "ありがとう", "romaji": "arigatou", "meaning": "謝謝" },
    { "kanji": "永遠", "kana": "えいえん", "romaji": "eien", "meaning": "永遠" },
    { "kanji": "記憶", "kana": "きおく", "romaji": "kioku", "meaning": "記憶" },
    { "kanji": "切ない", "kana": "せつない", "romaji": "setsunai", "meaning": "難過的、苦悶的" },
    { "kanji": "愛しい", "kana": "いとしい", "romaji": "itoshii", "meaning": "心愛的" },
    { "kanji": "恋人", "kana": "こいびと", "romaji": "koibito", "meaning": "戀人" },
    { "kanji": "温もり", "kana": "ぬくもり", "romaji": "nukumori", "meaning": "溫度、溫暖" },
    { "kanji": "溜息", "kana": "ためいき", "romaji": "tameiki", "meaning": "嘆氣" },
    { "kanji": "出会い", "kana": "であい", "romaji": "deai", "meaning": "相遇" },
    { "kanji": "別れ", "kana": "わかれ", "romaji": "wakare", "meaning": "離別" },
    { "kanji": "面影", "kana": "おもかげ", "romaji": "omokage", "meaning": "容貌、身影" },
    { "kanji": "胸", "kana": "むね", "romaji": "mune", "meaning": "胸口、內心" },
    { "kanji": "優しさ", "kana": "やさしさ", "romaji": "yasashisa", "meaning": "溫柔" },
    { "kanji": "嫉妬", "kana": "しっと", "romaji": "shitto", "meaning": "嫉妒" },
    { "kanji": "秘密", "kana": "ひみつ", "romaji": "himitsu", "meaning": "秘密" },

    // === 101 - 125: 四季、大自然與景象篇 ===
    { "kanji": "桜", "kana": "さくら", "romaji": "sakura", "meaning": "櫻花" },
    { "kanji": "花火", "kana": "はなび", "romaji": "hanabi", "meaning": "煙火 (米津玄師 - 打上花火)" },
    { "kanji": "向日葵", "kana": "ひまわり", "romaji": "himawari", "meaning": "向日葵" },
    { "kanji": "紅葉", "kana": "もみじ", "romaji": "momiji", "meaning": "楓葉" },
    { "kanji": "雪", "kana": "ゆき", "romaji": "yuki", "meaning": "雪" },
    { "kanji": "吹雪", "kana": "ふぶき", "romaji": "fubuki", "meaning": "暴風雪" },
    { "kanji": "海", "kana": "うみ", "romaji": "umi", "meaning": "海洋" },
    { "kanji": "海岸", "kana": "かいがん", "romaji": "kaigan", "meaning": "海岸" },
    { "kanji": "風", "kana": "かぜ", "romaji": "kaze", "meaning": "微風" },
    { "kanji": "嵐", "kana": "あらし", "romaji": "arashi", "meaning": "暴風雨" },
    { "kanji": "太陽", "kana": "たいよう", "romaji": "taiyou", "meaning": "太陽" },
    { "kanji": "夕日", "kana": "ゆうひ", "romaji": "yuuhi", "meaning": "夕陽" },
    { "kanji": "茜色", "kana": "あかねいろ", "romaji": "akaneiro", "meaning": "暗紅色、茜草色" },
    { "kanji": "四季", "kana": "しき", "romaji": "shiki", "meaning": "四季" },
    { "kanji": "季節", "kana": "きせつ", "romaji": "kisetsu", "meaning": "季節" },
    { "kanji": "春", "kana": "はる", "romaji": "haru", "meaning": "春天" },
    { "kanji": "夏", "kana": "なつ", "romaji": "natsu", "meaning": "夏天" },
    { "kanji": "秋", "kana": "あき", "romaji": "aki", "meaning": "秋天" },
    { "kanji": "冬", "kana": "ふゆ", "romaji": "fuyu", "meaning": "冬天" },
    { "kanji": "大自然", "kana": "だいしぜん", "romaji": "daishizen", "meaning": "大自然" },
    { "kanji": "雲", "kana": "くも", "romaji": "kumo", "meaning": "雲朵" },
    { "kanji": "雨", "kana": "あめ", "romaji": "ame", "meaning": "下雨" },
    { "kanji": "虹", "kana": "にじ", "romaji": "niji", "meaning": "彩虹" },
    { "kanji": "大地", "kana": "だいち", "romaji": "daichi", "meaning": "大地" },
    { "kanji": "地平線", "kana": "ちへいせん", "romaji": "chiheisen", "meaning": "地平線" },

    // === 126 - 150: 樂器、音響與舞台演唱篇 (MyGO!!!!!、BanG Dream感) ===
    { "kanji": "歌", "kana": "うた", "romaji": "uta", "meaning": "歌曲" },
    { "kanji": "唄", "kana": "うた", "romaji": "uta", "meaning": "古風/傳統歌謠" },
    { "kanji": "歌手", "kana": "かしゅ", "romaji": "kashu", "meaning": "歌手" },
    { "kanji": "歌詞", "kana": "かし", "romaji": "kashi", "meaning": "歌詞" },
    { "kanji": "音", "kana": "おと", "romaji": "oto", "meaning": "聲音" },
    { "kanji": "本音", "kana": "ほんね", "romaji": "honne", "meaning": "真心話" },
    { "kanji": "響き", "kana": "ひびき", "romaji": "hibiki", "meaning": "迴響、共鳴" },
    { "kanji": "楽器", "kana": "がっき", "romaji": "gakki", "meaning": "樂器" },
    { "kanji": "音響", "kana": "おんきょう", "romaji": "onkyou", "meaning": "音響" },
    { "kanji": "声", "kana": "こえ", "romaji": "koe", "meaning": "歌聲、人聲" },
    { "kanji": "叫び", "kana": "さけび", "romaji": "sakebi", "meaning": "吶喊" },
    { "kanji": "拍手", "kana": "はくしゅ", "romaji": "hakshu", "meaning": "鼓掌" },
    { "kanji": "舞台", "kana": "ぶたい", "romaji": "butai", "meaning": "舞台" },
    { "kanji": "奏でる", "kana": "かなでる", "romaji": "kanaderu", "meaning": "演奏" },
    { "kanji": "ピアノ", "kana": "ぴあの", "romaji": "piano", "meaning": "鋼琴" },
    { "kanji": "ギター", "kana": "ぎたー", "romaji": "gitaー", "meaning": "吉他" },
    { "kanji": "ドラム", "kana": "どらむ", "romaji": "doramu", "meaning": "爵士鼓" },
    { "kanji": "ベース", "kana": "べーす", "romaji": "beーsu", "meaning": "貝斯" },
    { "kanji": "リズム", "kana": "りずむ", "romaji": "rizumu", "meaning": "節奏" },
    { "kanji": "ライブ", "kana": "らいぶ", "romaji": "raibu", "meaning": "現場演唱會" },
    { "kanji": "バンド", "kana": "ばんど", "romaji": "bando", "meaning": "樂團" },
    { "kanji": "音符", "kana": "おんぷ", "romaji": "onpu", "meaning": "音符" },
    { "kanji": "和音", "kana": "わおん", "romaji": "waon", "meaning": "和弦" },
    { "kanji": "残響", "kana": "ざんきょう", "romaji": "zankyou", "meaning": "殘響、餘音" },
    { "kanji": "大歓声", "kana": "だいかんせい", "romaji": "daikansei", "meaning": "全場歡呼聲" },

    // === 151 - 175: 動作、速度與時間流逝篇 ===
    { "kanji": "走る", "kana": "はしる", "romaji": "hashiru", "meaning": "奔跑" },
    { "kanji": "跳ぶ", "kana": "とぶ", "romaji": "tobu", "meaning": "跳躍" },
    { "kanji": "叫ぶ", "kana": "さけぶ", "romaji": "sakebu", "meaning": "高喊" },
    { "kanji": "祈る", "kana": "いのる", "romaji": "inoru", "meaning": "祈禱" },
    { "kanji": "願う", "kana": "ねがう", "romaji": "negau", "meaning": "願望、期盼" },
    { "kanji": "忘れる", "kana": "わすれる", "romaji": "wasureru", "meaning": "忘記" },
    { "kanji": "覚える", "kana": "おぼえる", "romaji": "oboeru", "meaning": "記住" },
    { "kanji": "探す", "kana": "さがす", "romaji": "sagasu", "meaning": "尋找" },
    { "kanji": "見つける", "kana": "みつける", "romaji": "mitsukeru", "meaning": "找到" },
    { "kanji": "信じる", "kana": "しんじる", "romaji": "shinjiru", "meaning": "相信" },
    { "kanji": "迷う", "kana": "まよう", "romaji": "mayou", "meaning": "迷茫、迷路" },
    { "kanji": "始まる", "kana": "はじまる", "romaji": "hajimaru", "meaning": "開始" },
    { "kanji": "終わる", "kana": "おわる", "romaji": "owaru", "meaning": "結束" },
    { "kanji": "進む", "kana": "すすむ", "romaji": "susumu", "meaning": "前進" },
    { "kanji": "戻る", "kana": "もどる", "romaji": "modoru", "meaning": "返回" },
    { "kanji": "加速", "kana": "かそく", "romaji": "kasoku", "meaning": "加速" },
    { "kanji": "瞬間", "kana": "しゅんかん", "romaji": "shunkan", "meaning": "瞬間" },
    { "kanji": "時間", "kana": "じかん", "romaji": "jikan", "meaning": "時間" },
    { "kanji": "時代", "kana": "じだい", "romaji": "jidai", "meaning": "時代" },
    { "kanji": "歴史", "kana": "れきし", "romaji": "rekishi", "meaning": "歷史" },
    { "kanji": "過去", "kana": "かこ", "romaji": "kako", "meaning": "過去" },
    { "kanji": "現在", "kana": "げんざい", "romaji": "genzai", "meaning": "現在" },
    { "kanji": "刹那", "kana": "せつな", "romaji": "setsuna", "meaning": "剎那" },
    { "kanji": "永遠", "kana": "えいえん", "romaji": "eien", "meaning": "永遠" },
    { "kanji": "時計", "kana": "とけい", "romaji": "tokei", "meaning": "時鐘" },

    // === 176 - 200: 抽象概念、勝利與終局篇 ===
    { "kanji": "理想", "kana": "りそう", "romaji": "risou", "meaning": "理想" },
    { "kanji": "現実", "kana": "げんじつ", "romaji": "genjitsu", "meaning": "現實" },
    { "kanji": "幻想", "kana": "げんそう", "romaji": "gensou", "meaning": "幻想" },
    { "kanji": "妄想", "kana": "もうそう", "romaji": "mousou", "meaning": "妄想" },
    { "kanji": "真実", "kana": "しんじつ", "romaji": "shinjitsu", "meaning": "真實" },
    { "kanji": "正解", "kana": "せいかい", "romaji": "seikai", "meaning": "正確答案" },
    { "kanji": "間違い", "kana": "まちがい", "romaji": "machigai", "meaning": "錯誤" },
    { "kanji": "成功", "kana": "せいこう", "romaji": "seikou", "meaning": "成功" },
    { "kanji": "失敗", "kana": "しっぱい", "romaji": "shippai", "meaning": "失敗" },
    { "kanji": "挑戦", "kana": "ちょうせん", "romaji": "chousen", "meaning": "挑戰" },
    { "kanji": "冒険", "kana": "ぼうけん", "romaji": "bouken", "meaning": "冒險" },
    { "kanji": "旅人", "kana": "たびびと", "romaji": "tabibito", "meaning": "旅人" },
    { "kanji": "伝説", "kana": "でんせつ", "romaji": "densetsu", "meaning": "傳說" },
    { "kanji": "王者", "kana": "おうじゃ", "romaji": "ouja", "meaning": "王者" },
    { "kanji": "頂点", "kana": "ちょうてん", "romaji": "chouten", "meaning": "頂點" },
    { "kanji": "栄光", "kana": "えいこう", "romaji": "eikou", "meaning": "榮光" },
    { "kanji": "奇跡", "kana": "きせき", "romaji": "kiseki", "meaning": "奇蹟" },
    { "kanji": "運命", "kana": "うんめい", "romaji": "unmei", "meaning": "命運" },
    { "kanji": "宿命", "kana": "しゅくめい", "romaji": "shukumei", "meaning": "宿命" },
    { "kanji": "天国", "kana": "てんごく", "romaji": "tengoku", "meaning": "天國" },
    { "kanji": "地獄", "kana": "じごく", "romaji": "jigoku", "meaning": "地獄" },
    { "kanji": "光栄", "kana": "こうえい", "romaji": "kouei", "meaning": "光榮" },
    { "kanji": "最高", "kana": "さいこう", "romaji": "saikou", "meaning": "最高" },
    { "kanji": "最後", "kana": "さいご", "romaji": "saigo", "meaning": "最後" },
    { "kanji": "終焉", "kana": "しゅうえん", "romaji": "shuuen", "meaning": "終焉、迎向結局" }
];